### ISSUE TITLE
Running docker-compose up throws an error that `scale` is not supported

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#691] opened 2021-04-29 20:42 UTC
**Describe the bug**
A user in our Discord server said he was having an issue with running `docker-compose`.
Here's the [link](https://discord.com/channels/667044843901681675/832331828072939530/837364652434259989) to the start of the discussion.

He pointed out that this was an issue with v3 of docker compose file format, hence his mention and error of `scale`  not being supported in `docker-compose.yml`. 

**To Reproduce**
Waiting for @kesarito to provide a repro

**Expected behavior**
Running `docker-compose up` should start the OE services with no errors thrown.

**Additional context**
Will update this issue as we get a repro and more info.
Also, has anyone else experienced this issue before?

**Comment by snario** [comment] 2021-04-29 21:14
Duplicate of #690

**Closed by snario** 2021-04-29 21:14 UTC
