### ISSUE TITLE
EVM incompatibility when a contract selfdestructs and sends its balance to itself

### ISSUE THREAD

**Issue by maraoz** [ethereum-optimism/optimism#2604] opened 2022-05-23 22:36 UTC
**Describe the bug**
I was playing around with Optimism yesterday and I found that if a contract selfdestructs and sends the remaining balance to itself, that balance remains on the contract after it is destroyed. This is different from the EVM behavior, which in that case leaves the contract with 0 balance, effectively destroying some ether. 

I later found that @saurik already reports this on his ["Attacking an Ethereum L2 with Unbridled Optimism" blog post](https://www.saurik.com/optimism.html). Maybe this EVM discrepancy should be added to [Known Issues](https://community.optimism.io/docs/developers/known-issues/#) page on the docs? I don't think fixing it merits a hard fork, it seems inocuous.

**To Reproduce**
1. Deploy a contract that has some function which selfdestructs the contract sending remaining balance to itself. eg:
```
contract Suicidal {
    constructor() payable {
      selfdestruct(payable(address(this)));
    }
}
```
2. Deploy that contract and execute the selfdestruct op.
4. Check the contract's balance
5. Should be 0, but it's not.

**Expected behavior**
EVM equivalence would require this scenario to leave the contract with 0 balance.

**Comment by smartcontracts** [comment] 2022-05-24 07:08
I agree that this should be included in Known Issues. Note that this will be fixed as part of the Bedrock upgrade. It's strongly recommended that you do not write contract logic based on this behavior, since it's not the expected behavior on Ethereum and will be removed in Bedrock.

**Closed** 2023-06-16 19:15 UTC
Labels: C-bug, P-wontfix, C-bedrock-fixes-this
