### ISSUE TITLE
How do I run just a L2 full node for RPC access?

### ISSUE THREAD

**Issue by diwu1989** [ethereum-optimism/optimism#2605] opened 2022-05-24 06:42 UTC
I would like to run just the L2 full node as part of the network and receive the L2 state + be able to make local RPC calls to the L2 mainnet.

I see that there's a docker-compose for local testnet:
https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker-compose.yml

But I don't want a local testnet.
When I run just the L2geth, it doesn't seem to sync with the network, and it's not clear what I should be configuring to have just a full node L2geth.

Please provide instructions and docker-compose example for this.

**Comment by diwu1989** [comment] 2022-05-24 07:11
Thanks, so just 2 components, DTL and the L2geth.

Does the L2Geth gossip with other L2geth nodes on the network via P2P to get pending transactions?
I know that the sequencer has no mempool and just directly append the TX in FIFO order to the state transitions, but would L2Geth broadcast pending TX into the network and the Sequencer?

**Comment by smartcontracts** [comment] 2022-05-24 07:18
> Thanks, so just 2 components, DTL and the L2geth.
> 
> Does the L2Geth gossip with other L2geth nodes on the network via P2P to get pending transactions? I know that the sequencer has no mempool and just directly append the TX in FIFO order to the state transitions, but would L2Geth broadcast pending TX into the network and the Sequencer?

Currently, no, there is no L2 p2p network. This will change as part of the upcoming Bedrock upgrade where p2p will be reintroduced. At the moment, the DTL (when running in L1 sync mode) will get blocks directly from L1 (Ethereum). This will always lag a bit behind the L2 system because the Sequencer can wait several minutes before publishing blocks to Ethereum. If you want to get transactions quickly, you can run in "L2 sync mode" which will get transactions directly from the Sequencer.

When Bedrock goes live, you will be able to get "unsafe" blocks from the L2 p2p network which will become "safe" blocks when confirmed/published to Ethereum.

**Comment by diwu1989** [comment] 2022-05-24 07:30
When it runs in L2 sync mode, is it just making repeated HTTP polling API calls to https://mainnet.optimism.io  where the sequencer lives? Or is it somehow connecting to the sequencer node via P2P?

**Comment by diwu1989** [comment] 2022-05-24 07:32
Also, sequencer seems to live in GKE, but which GKE data center region should I run my infra on to get lower latency to sequencer? GCP East? MidWest? West?

**Comment by diwu1989** [comment] 2022-05-25 04:25
If I build the bedrock develop branch, does that sync up with existing non bedrock clients?

**Comment by smartcontracts** [comment] 2022-05-25 19:24
> If I build the bedrock develop branch, does that sync up with existing non bedrock clients?

Bedrock currently does not sync with non-bedrock clients (yet). 


> Also, sequencer seems to live in GKE, but which GKE data center region should I run my infra on to get lower latency to sequencer? GCP East? MidWest? West?

Unsure, can ask.



> When it runs in L2 sync mode, is it just making repeated HTTP polling API calls to https://mainnet.optimism.io where the sequencer lives? Or is it somehow connecting to the sequencer node via P2P?

Yes, it's basically making repeated calls to the Sequencer. No true p2p in the current iteration.

**Comment by smartcontracts** [comment] 2022-05-26 21:41
> Mmmm http polling is quite inefficient, in theory, should i be able to just modify the DTL to use websocket and get pushed new data from the centralized sequencer? Or is there some inherent design reason that it's HTTP poll vs websocket push?

Hmmm yes presumably it should be possible to modify the DTL to use websockets. We haven't done it because the current setup has been "good enough" for the moment and will be deprecated when Bedrock rolls around in a few months.

**Comment by diwu1989** [comment] 2022-05-27 06:11
In bedrock, is the L2 pendings also being gossiped to all of the full nodes? Or only the L2 pending block being gossiped?
Does this also mean that in bedrock, p2p will be able to connect to all potential sequencers?

**Comment by crypto-only** [comment] 2022-06-01 05:54
The DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT is same as public RPC URL https://mainnet.optimism.io/ . I will get Too many requests error when using https://mainnet.optimism.io/ as RPC URL, will I get same error if I run my own node? For example, I will not get too many requests error to request my own Ethereum node.

**Comment by diwu1989** [comment] 2022-06-02 03:34
They throttled stuff today due to congestion, use infura instead

**Comment by vae520283995** [comment] 2022-06-02 03:53
> The DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT is same as public RPC URL https://mainnet.optimism.io/ . I will get Too many requests error when using https://mainnet.optimism.io/ as RPC URL, will I get same error if I run my own node? For example, I will not get too many requests error to request my own Ethereum node.

Me too, can we start this service ourselves?

**Comment by diwu1989** [comment] 2022-06-06 00:10
@smartcontracts i started looking at Arbitrum too, and in their architecture, their main sequencer is sending a websocket feed of all L2 TX at wss://arb1.arbitrum.io/feed for full nodes to ingest. This is as opposed to a pull model where all of the full nodes have to pull for pending blocks from the OP sequencer.

It would be nice for Optimism to also provide sequencer websocket feed vs just having DTLs configured to poll every 100ms.

**Comment by smartcontracts** [comment] 2022-06-06 23:26
> @smartcontracts i started looking at Arbitrum too, and in their architecture, their main sequencer is sending a websocket feed of all L2 TX at wss://arb1.arbitrum.io/feed for full nodes to ingest. This is as opposed to a pull model where all of the full nodes have to pull for pending blocks from the OP sequencer.
> 
> It would be nice for Optimism to also provide sequencer websocket feed vs just having DTLs configured to poll every 100ms.

We won't be implementing this for the current iteration. For Bedrock, nodes will sync over a p2p network which should make this problem go away. I agree the current DTL sync is ugly but better to focus on shipping Bedrock than fixing the DTL at this point. It's "good enough" for the next few months until Bedrock completely replaces it.

**Comment by diwu1989** [comment] 2022-06-06 23:52
Is there a separate branch where I can run op-replica on Bedrock testnet?
I want to get an early head start and get all of my arb + liquidation systems ready.

**Comment by smartcontracts** [comment] 2022-06-07 01:18
Not quite ready yet. Bedrock devnet not live yet.

**Comment by smartcontracts** [comment] 2022-06-09 17:49
Gonna close this, feel free to ask further questions on discord if you're looking for more assistance running a node!

**Closed by smartcontracts** 2022-06-09 17:49 UTC
