### ISSUE TITLE
Watcher does NOT catch silently failed txs

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#741] opened 2021-05-04 00:26 UTC
**Describe the bug**
After debugging an issue with @K-Ho and Ale from Synthetix, we found that his local message relayer was actually being deployed. However, Ale's withdrawal tx was failing silently which his local watcher was able to detect.

**Steps to reproduce**
1. Git clone repo: `git clone git@github.com:Synthetixio/synthetix.git`
2. Checkout the develop branch: `git checkout develop`
3. Install deps: `npm i`
4. Deploy contracts: `node publish deploy-ovm-pair
5. Run tests: `npm run test:prod:ovm`
6. See tests hang:

**Screenshots**
Screenshot taken by Ale of his tests failing in his CI:

![image](https://user-images.githubusercontent.com/37757724/116948855-344bc080-ac46-11eb-8688-12765c767237.png)

**Expected behavior**
Watcher should pick up all deposits and withdrawals on the other side, even if they revert

**Comment by TransmissionsDev** [comment] 2021-05-04 00:31
Looks like a duplicate of: https://github.com/ethereum-optimism/optimism/issues/602

**Comment by platocrat** [comment] 2021-05-04 00:33
@TransmissionsDev you're absolutely right. 

@K-Ho @snario could we listen to this young chap more often?

**Closed** 2021-05-04 00:33 UTC
