### ISSUE TITLE
JSON RPC batch requests are not supported

### ISSUE THREAD

**Issue by vbaranov** [ethereum-optimism/optimism#2021] opened 2022-01-17 09:36 UTC
I'm testing Kovan Optimism and discovered that JSON RPC batch requests are not supported:

> curl -X POST --data '[{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xE9304", false],"id":83},{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xE855C", false],"id":84}]' https://kovan.optimism.io/
> {"jsonrpc":"2.0","error":{"code":-32700,"message":"parse error"},"id":null}

Do you plan to support them or perhaps it has been already added in the latest version of the client?

**Comment by smartcontracts** [comment] 2022-01-18 04:46
This may be a configuration issue with the proxy that sits in front of kovan.optimism.io. I'm not sure why batch requests would be unsupported, I don't think we've removed them from Geth. Will flag this.

**Comment by Inphi** [comment] 2022-01-18 04:53
The problem is in [proxyd](https://github.com/ethereum-optimism/optimism/blob/3174f034da022ac7ebcfde4ebd08961e377b43c3/go/proxyd/rpc.go#L57) itself. We reject batched RPCs for some reason. I don't think this is the intended behavior.

**Comment by vbaranov** [comment] 2022-01-18 14:06
As additional info, If I run Optimism node locally by following this guide https://community.optimism.io/docs/developers/l2/dev-node.html using Docker images, JSON RPC batch requests work fine.

**Comment by tynes** [comment] 2022-01-18 20:39
This is a known issue with the public endpoint, see: https://github.com/ethereum-optimism/optimism/pull/1987#issuecomment-1012344285

If you require this functionality right now, please run your own replica or use Quicknode/Infura/Alchemy

**Comment by mslipper** [comment] 2022-01-21 18:11
This is fixed on the public endpoint now.

**Closed by mslipper** 2022-01-21 18:11 UTC
Labels: C-bug, P-confirmed, M-l2geth
