### ISSUE TITLE
`estimateGas` reverts, but the transaction succeeds with a hardcoded `gasLimit`

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#664] opened 2021-04-28 03:06 UTC
**Describe the bug**
In ChainLink's [LinkToken](https://github.com/smartcontractkit/LinkToken) integration tests, 3/7 tests fail. Those that do fail involve contract calls that should revert. However, instead of a revert message being returned, the familiar `cannot estimate gas` error is thrown.

**To Reproduce**
1. `git clone https://github.com/smartcontractkit/LinkToken.git`
2. `git checkout feature/ovm-integration-upstream-changes`
3. Start the docker containers under `optimism/ops` to start a local OE network
3. Back in the LinkToken project directory, run:  `yarn && yarn setup && yarn test:integration../test/v0.7/bridge/optimism/OVM_L2ERC20Gateway.test.ts`
4. See the familiar error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit
```

**Expected behavior**
A transaction that fails `estimateGas` should not succeed with a hardcoded `gasLimit`

**Related issues**
#474 
#543

**Comment by TransmissionsDev** [comment] 2021-04-28 03:29
Hasn't there been an issue up for this for a while?

**Comment by platocrat** [comment] 2021-04-28 03:39
> Hasn't there been an issue up for this for a while?

yes. #474 is one related issue and #543 is perhaps another

**Comment by platocrat** [comment] 2021-04-28 14:55
@K-Ho closing since this is a duplicate of #664

**Comment by K-Ho** [comment] 2021-04-28 19:11
@platocrat The expected behavior listed here isn't actually right. Chainlink is getting `UNPREDICTABLE_GAS_LIMIT` when trying to `estimateGas` but the tx succeeds with a static gasLimit.

**Comment by TransmissionsDev** [comment] 2021-04-28 19:24
> @platocrat The expected behavior listed here isn't actually right. Chainlink is getting `UNPREDICTABLE_GAS_LIMIT` when trying to `estimateGas` but the tx succeeds with a static gasLimit.

@K-Ho I've noticed that txs always succeed with a static gas limit actually...

**Comment by platocrat** [comment] 2021-04-28 19:33
@K-Ho just to confirm that this really is the same issue that we see for contract calls that revert, here are the full error messages for the 2 Waffle-based tests that fail with this error:

<img width="941" alt="Screen Shot 2021-04-28 at 2 27 23 PM" src="https://user-images.githubusercontent.com/37757724/116461427-daa25b00-a82d-11eb-9672-10f911a9608f.png">

I highlighted the `code=UNPREDICTABLE_GAS_LIMIT` field, which you can see appears in both error messages.

**NOTE**: I can confirm that specifying the gas limit to `8999999` for the calls in these two tests does makes the txs succeed.

**Comment by snario** [comment] 2021-04-28 20:24
This is **not** a duplicate of #474. That issue describes “estimateGas does not provide the revert reason” and this issue describes: “estimateGas reverts, but the transaction succeeds with a hardcoded gasLimit”

**Comment by tynes** [comment] 2021-04-30 03:28
I believe the problem is with `simulateMessage()`. It is the main difference between a regular transaction and `eth_call`, `eth_estimateGas` uses `eth_call`

**Comment by platocrat** [comment] 2021-05-03 18:07
@tynes @snario I re-ran the integration test for the hardhat example in the monorepo and get an odd type error.

The error is below:
```
   Error: invalid BigNumber string (argument="value", value="auto", code=INVALID_ARGUMENT, version=bignumber/5.1.0)
      at Logger.makeError (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.throwError (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at Logger.throwArgumentError (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
      at Function.BigNumber.from (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:240:27)
      at JsonRpcProvider.provider.getGasPrice (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/packages/hardhat-ovm/src/index.ts:225:26)
      at Wallet.<anonymous> (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:139:36)
      at step (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/abstract-signer/lib/index.js:48:23)
      at Object.next (/Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/abstract-signer/lib/index.js:29:53)
      at /Users/platocrat/Documents/GitHub/OptimismPBC/Optimism/optimism/node_modules/@ethersproject/abstract-signer/lib/index.js:23:71
      at new Promise (<anonymous>)
```

The error points to [`optimism/packages/hardhat-ovm/src/index.ts:225:26`](https://github.com/ethereum-optimism/optimism/blob/562266063f6bea20fdb94fbf0b4ebd3767e678e7/packages/hardhat-ovm/src/index.ts#L226).
This error is received after pulling and building @tynes's branch from [ethereum-optimism/optimism/pull/721](https://github.com/ethereum-optimism/optimism/pull/721).

@K-Ho From this new error shown above, I believe [ethereum-optimism/optimism/pull/721](https://github.com/ethereum-optimism/optimism/pull/721) should warrant a separate GH issue.
I also think we can conclude that the original issue here is resolved as per Kevin's response earlier:

> @platocrat The expected behavior listed here isn't actually right. Chainlink is getting `UNPREDICTABLE_GAS_LIMIT` when trying to `estimateGas` but the tx succeeds with a static gasLimit.

**Comment by gakonst** [comment] 2021-05-03 18:56
@platocrat this error you got is because there is no `gasPrice: 0` parameter in your hardhat config.

**Comment by platocrat** [comment] 2021-05-03 20:40
I'm confirming that this issue is fixed by [ethereum-optimism/optimism/pull/721](https://github.com/ethereum-optimism/optimism/pull/721)!!

**Comment by gakonst** [comment] 2021-05-03 21:28
What's the exact fix by 721? Do you get proper revert messages?

**Comment by platocrat** [comment] 2021-05-04 00:20
> What's the exact fix by 721? Do you get proper revert messages?

The fix appears to be that we no longer need to specify a hardcoded `gasLimit`.

**Comment by tynes** [comment] 2021-05-04 00:26
> The fix appears to be that we no longer need to specify a hardcoded gasLimit.

This is the result of the fix

> What's the exact fix by 721? Do you get proper revert messages?

The problem was that the interface between userland and the system contracts was not defined. `ExecutionManager.run` returned a different ABI encoded returndata compared to `ExecutionManager.simulateMessage`. The returndata was parsed by simply slicing bytes which worked when the returndata was a single type but then broke when it was multiple types.

`eth_estimateGas` calls `eth_call` under the hood a bunch of times, so the problem was also present in `eth_call` - basically the return value of the `eth_call` wouldn't be deserialized correctly by `l2geth` and it would interpret the returndata as indicating that the transaction reverted when it actually didn't. This would result in the message `Error: cannot estimate gas; transaction may fail or may require manual gas limit` because `l2geth` thought that the tx would revert

**Comment by platocrat** [comment] 2021-05-04 01:34
@K-Ho @tynes Re-ran integration tests of ChainLink's old LinkToken branch `feature/ovm-integration-upstream-changes` using recent fetched commits of the monorepo.

The tests that are supposed to revert still revert with the same `UNPREDICTABLE_GAS_LIMIT` error:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit
```

I also confirmed that adding a hardcoded gasLimit of `8999999` is still a workaround.

**Comment by K-Ho** [comment] 2021-05-04 03:13
@platocrat - are you still seeing this `estimateGas` error with the Waffle ERC20 Example tests? If so, I think the next step would be to comment out parts of execution until we nail down the exact section that causes `estimateGas` to fail

**Comment by platocrat** [comment] 2021-05-04 22:39
Regarding https://github.com/ethereum-optimism/optimism/issues/664 and https://github.com/ethereum-optimism/optimism/pull/721:
1. `l1-l2-deposit-withdrawal` outside of monorepo (because of current issue with installing `@eth-optimism/contracts` as a dep when inside monorepo)
   a. I ran the `optimism/ops` containers from the `l2geth/fix-returndata` branch (from [pull/721](https://github.com/ethereum-optimism/optimism/pull/721)) and ran the `l1-l2-deposit-withdrawal script`.
   b. Without specifying `gasPrice: 0` nor `gasLimit: 8999999`, none of the transactions in the `example.js` script will be submitted successfully.
   c. Specifying only `gasPrice: 0` in every contract call results in the errors thrown, as in [issue/664](https://github.com/ethereum-optimism/optimism/issues/664), for every call
   d. Specifying both `gasPrice: 0` nor `gasLimit: 8999999` results in the script working as expected, all transactions are submitted successfully
2. `Waffle-ERC20-Example` within monorepo
   e. [Tests] As @K-Ho pointed out when running the Waffle tests in `optimism/examples/waffle`, all tests pass without any changes.
   f. This means that we do NOT need to hardcode a `gasPrice` nor `gasLimit` anywhere
3. `Truffle-ERC20-Example` outside of monorepo (no concerning reason, just quicker for me -- I believe we can now finalize https://github.com/ethereum-optimism/optimism/pull/666 ):
   g. [Tests] TL;DR is that tests fail ONLY if `gasPrice: 0` is not set everywhere, including in all  migrations scripts, when running tests
   h. [Deployments] Running migrations is successful after setting`gasPrice: 0` in migrations file(s).
4. `optimism-tutorial` within monorepo
   i. [Tests] Will only pass if we set `gasPrice: 0` in the `hardhat.config.*`
   j. [Deployments] Successful even WITHOUT a hardcoded `gasLimit` and `gasPrice`

cc: @snario @gakonst @K-Ho @tynes

**Comment by smartcontracts** [comment] 2021-05-10 21:29
@platocrat I'm unable to reproduce this on `v0.3.0-rc`. We might've fixed the problem in that branch.

**Comment by platocrat** [comment] 2021-05-10 21:35
You need to comment out line 8 in `test/helpers/optimism/index.ts`

**Comment by smartcontracts** [comment] 2021-05-10 21:48
I was able to fix this problem by using `v0.3.0` (now merged into master!) and changing the tests as follows:

1. Remove https://github.com/smartcontractkit/LinkToken/blob/8731d538f1290ac6bf6bdcd6a5aa92ae8a8125d5/test/helpers/optimism/index.ts#L8
2. Modify tests:

```diff
     it('can NOT deposit without  access (gateway role)', async () => {
-      const depositTx = await l2Token.deposit(oe.l2Wallet.address, 100, h.optimism.TX_OVERRIDES_OE_BUG)
-      // TODO: fetch revert reason
-      // revert: LinkTokenChild: missing role
-      await h.txRevert(depositTx.wait())
+      await expect(
+        l2Token.deposit(oe.l2Wallet.address, 100, h.optimism.TX_OVERRIDES_OE_BUG)
+      ).to.be.revertedWith('No access')
     })
     it('owner can migrate to a new gateway', async () => {
@@ -221,10 +220,11 @@ describe(`LinkTokenChild ${Versions.v0_7}`, () => {
       const removeAccessTx = await l2Token.removeAccess(owner.address)
       await removeAccessTx.wait()
       // Owner deposit fails
-      const depositTx = await l2Token.deposit(owner.address, 100, h.optimism.TX_OVERRIDES_OE_BUG)
       // TODO: fetch revert reason
       // revert: LinkTokenChild: missing role
-      await h.txRevert(depositTx.wait())
+      await expect(
+        l2Token.deposit(owner.address, 100, h.optimism.TX_OVERRIDES_OE_BUG)
+      ).to.be.revertedWith('No access')
       // TODO: owner renounce ownership
     })
```

**Comment by gakonst** [comment] 2021-05-11 07:12
Of note, Kelvin's approach above is the correct way to do it in JS. The way the tests were written before, they'd fail even in EVM mode because you're awaiting a failing transaction with an overridden gas limit.

**Comment by K-Ho** [comment] 2021-05-12 18:41
re-opening this issue - here's Chainlink still seeing this issue appear:
This PR is green with static gasLimit: https://github.com/smartcontractkit/LinkToken/pull/33
This PR is red with NO static gasLimit: https://github.com/smartcontractkit/LinkToken/pull/37 (just this one change)
This is the failure: https://github.com/smartcontractkit/LinkToken/runs/2569267264?check_suite_focus=true (UNPREDICTABLE_GAS_LIMIT)

**Comment by platocrat** [comment] 2021-05-12 19:56
I was able to repro https://github.com/smartcontractkit/LinkToken/pull/37 and https://github.com/smartcontractkit/LinkToken/pull/33 locally.
Going to inspect further

**Comment by platocrat** [comment] 2021-05-12 20:42
I resolved the `UNPREDICTABLE_GAS_LIMIT` errors in the two tests in https://github.com/smartcontractkit/LinkToken/pull/37 using Kelvin's approach earlier above:

```diff
      it('can NOT deposit without  access (gateway role)', async () => {
-      const mintTx = await l2Token.mint(oe.l2Wallet.address, 100, optimism.TX_OVERRIDES_BUG)
-      // TODO: fetch revert reason
        // revert: 'No access'
-      await h.txRevert(mintTx.wait())
+     const mintTx = l2Token.mint(oe.l2Wallet.address, 100, optimism.TX_OVERRIDES_BUG)
+     await expect(mintTx).to.be.revertedWith('No access')
})
      it('owner can migrate to a new gateway', async () => {
-      const mintTx = await l2Token.mint(owner.address, 100, optimism.TX_OVERRIDES_BUG)
-      // TODO: fetch revert reason
-      // revert: 'No access'
-      await h.txRevert(mintTx.wait())
+       const mintTx = l2Token.mint(owner.address, 100, optimism.TX_OVERRIDES_BUG)
+       await expect(mintTx).to.be.revertedWith('No access')
```

**Comment by snario** [comment] 2021-05-12 23:39
As @gakonst mentioned, it looks like the test was just written incorrectly.

**Closed by snario** 2021-05-12 23:39 UTC
Labels: A-geth, A-integration-tests, C-bug, P-confirmed
