### ISSUE TITLE
Request for method 'eth_chainId on https://mainnet.optimism.io failed

### ISSUE THREAD

**Issue by lkyee** [ethereum-optimism/optimism#1849] opened 2021-12-03 04:29 UTC
**Describe the bug**
cannot add the Optimistic Ethereum network to my wallet,please help me

**Comment by t0od** [comment] 2021-12-03 06:03
curl https://mainnet.optimism.io \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}'

I just tried this command and it seems to work

**Comment by t0od** [comment] 2021-12-03 06:37
Related to #1598

**Comment by smartcontracts** [comment] 2021-12-03 14:41
mainnet.optimism.io points to nodes hosted by QuickNode. I think QuickNode blocks users from certain regions/IPs for compliance reasons. Could be worth hosting multiple public RPC endpoints in case QuickNode is erroneously blocking a user.

**Comment by optimisticben** [comment] 2021-12-03 15:01
We did have some downtime in the eastern region according to the [public dashboard](https://public-grafana.optimism.io/d/9hkhMxn7z/public-dashboard?orgId=1&from=1638318050351&to=1638483140115&var-network=mainnet&var-prometheus_replica=prometheus-k8s-0). Are you still having a problem accessing the endpoint?

**Comment by smartcontracts** [comment] 2021-12-03 16:44
Going to close this as a dupe of #1598, feel free to keep discussing here if you'd like but let's use #1598 as the main point of reference for users who are having this issue.

**Closed** 2021-12-03 16:47 UTC
