### ISSUE TITLE
NFT bridge between L1 and Optimism

### ISSUE THREAD

**Issue by sam-goldman-zz** [ethereum-optimism/optimism#2421] opened 2022-04-05 18:02 UTC
The purpose of this issue is to solicit feedback on an initial proposal for an ERC721 bridge between L1 and Optimism. The bridge allows owners of L1 NFTs to make deposits into L2 and withdrawals back to L1 in the same manner that ERC20s can be transferred using the [Standard Token Bridge](https://community.optimism.io/docs/developers/bridge/standard-bridge/#).

The relevant code can be found in [this PR](https://github.com/ethereum-optimism/optimism/pull/2577) or in the standalone repo [here](https://github.com/sam-goldman/optimism-nft-bridge). All contracts have been tested locally. For more information regarding the bridge, check out [these slides](https://docs.google.com/presentation/d/e/2PACX-1vQDgyIjiWeXjkR3Yq-DDZSnyGqvxQ5efrY5WrwgRg7YjumPegQzYMaGwOHtYK_R5SGw6EGZT6_CGju1/pub?start=false&loop=false&delayms=3000&slide=id.g120f23c86d9_0_0) (credit goes to Mark!)

The design of the ERC721 Bridge is almost exactly the same as the Standard Token Bridge, with one main difference: token URIs are transferred off-chain using a permissioned oracle. The reason for this design choice is mostly due to the cost of transferring a token URI from L1 to L2 on-chain, which can be expensive since it is a large string. Also, it is common for NFT projects to change token URIs for various reasons, which means users would need to pay gas fees every time they want to to update their L2 token URI. We view this as a temporary solution until it is possible to read L1 state from L2, which would allow us to permissionlessly view tokenURIs from L2 without using an oracle. To be clear, only token URIs would be transferred off-chain; token IDs would be sent on-chain.

We'd love to hear the community's feedback on the design of the bridge, as well as the following open questions:
- What is the best way to handle the transfer of token URIs from L1 to L2?
- Should there be a token list to maintain a source of truth for high-profile NFT projects, similar to [Optimism's ERC20 Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/optimism.tokenlist.json)?
  - Who would maintain this token list?

**Comment by annieke** [comment] 2022-04-08 21:34
the optimism team (@maurelian @bdresser me) and quixotic (@sam-goldman @markdawson) met about this yesterday, and we have some open questions for reviewers!

1. How should we deal with TokenURIs?
    - We could use a trusted oracle to retrieve URI from L1 to include on L2. This could also periodically poll for updates.
    - We could send tokenURI over the bridge. This might be very expensive for users (unless we hash the data or do something fancy.)
2. How does the frontend know which L2 contract to mint from?
    - If the L2 contract is deployed form the standard factory, can we use on-chain data to look up the address used by previous versions of the same NFT?
    - For custom L2 contracts, how should we manage the token list? Can only the original core team get their custom contract added to the token list? Or can anyone? Which teams are responsible for approving requests?
3.  If users bridge an NFT before that NFT collection’s canonical/custom contract exists, what’s the process for swapping the “factory” NFT for the “canonical” one? Should we have a swap/exchange functionality?
4. Will NFT/collection devs be upset about permissionless bridging?

**Comment by xuannu-eth** [comment] 2022-04-13 22:11
hey! sharing some initial feedback as one of the creators of @crypto-coven after getting a ping from indreams.eth—i'm not familiar at all with l2s/bridging, so please feel free to take or leave any of these questions/comments!

**token uris**: using an oracle sounds reasonable as an interim solution. are there any downsides other than that it's happening off-chain and needs to be periodically refreshed?

**permissionless bridging**: speaking for ourselves, i can't see why we'd have any objections, assuming that it doesn't introduce any side effects for other tokens in the collection or the collection as a whole.

**managing the token list**: restricting adding a canonical contract to the owner address of the l1 contract sounds like it'd probably be the route to go!

**multiple l2 contracts**: this question feels like the biggest issue for me on a few levels:

1. i can imagine changing the functionality of an nft to a standard factory nft becoming really fraught in a number of ways. two examples that come to mind are soulbound nfts and loanable nfts. neither feature is popular, but it's also not that uncommon to experiment with erc-721 contracts, and permissionless bridging with changed functionality feels like it could be... quite dangerous? i saw in the deck that the concern was malicious contracts; i'd be curious to know more about how that risk could manifest.
2. fragmentation across an l2 would also be pretty undesirable—not just for liquidity, but for all kinds of functionality that you might want to build on top of a collection. has there been consideration around consolidating previously bridged nfts after a canonical contract exists?

**Comment by sam-goldman** [comment] 2022-04-15 05:19
For the token URI issue, Mark and I think it’d be best to follow EIP-681: https://eips.ethereum.org/EIPS/eip-681. This would allow L2 ERC721 contracts to direct the client to the correct L1 ERC721 contract to retrieve the token URI. This means that the URI on L1 would remain the source of truth, and users would only need to trust that the front-end they are using is displaying the correct information (i.e. it isn’t malicious).

**Comment by strollinghome** [comment] 2022-04-15 13:19
> For the token URI issue, Mark and I think it’d be best to follow EIP-681: https://eips.ethereum.org/EIPS/eip-681.

Interesting, what would be the benefits of EIP-681 over [EIP-3668](https://eips.ethereum.org/EIPS/eip-3668)?

**Comment by markdawson** [comment] 2022-04-18 22:39
> > For the token URI issue, Mark and I think it’d be best to follow EIP-681: https://eips.ethereum.org/EIPS/eip-681.
> 
> Interesting, what would be the benefits of EIP-681 over [EIP-3668](https://eips.ethereum.org/EIPS/eip-3668)?

EIP-681 is much more simple than EIP-3668 (and we don't really need EIP-3668's flexibility).

Using EIP-681, the layer 2 contract's `tokenURI` would return a link that looks like this:

`ethereum:0x8C0ef71B6FFB7786db4b4b00eD2503c8896e6038@42/tokenUri?tokenId=1`  

This means the client should go look up the result of `tokenURI` in the layer 1 contract (in this case `@42` means to look up on chainId 42 which is the kovan testnet). I think of this as similar to an IPFS lookup in that it's the client's job to figure out how to connect to the URI even if it's not an HTTP uri.

EIP-3668 would revert with error `OffchainLookup` and specify an array of URLs and a callback function. Returning an error for intended behavior might be sort of surprising and imply something is wrong. We also don't need a full array of URLs or a callback function, so the power of EIP-3668 isn't necessary.

**Comment by outdoteth** [comment] 2022-04-26 19:27
Is it possible to have the token list maintained by a DAO?

+1 for EIP-681. Very elegant.

**Comment by rzmahmood** [comment] 2022-05-02 22:44
Curious on the usage of EIP-681 vs https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-19.md

**Comment by markdawson** [comment] 2022-05-02 23:01
> 

I think the Optimism product team is actively thinking about how to maintain the token list. I think the ideal is that eventually it is maintained by a decentralized group but might begin with a smaller group that's easier to coordinate.

**Comment by markdawson** [comment] 2022-05-02 23:01
> Is it possible to have the token list maintained by a DAO?
> 
> +1 for EIP-681. Very elegant.

I think the Optimism product team is actively thinking about how to maintain the token list. I think the ideal is that eventually it is maintained by a decentralized group but might begin with a smaller group that's easier to coordinate.

**Comment by markdawson** [comment] 2022-05-02 23:02
> Curious on the usage of EIP-681 vs https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-19.md

I haven't seen CAIP-19. Both standards seem like they would work. Do you know of any dapps that use CAIP-19?

**Comment by sam-goldman** [comment] 2022-05-04 19:30
> **multiple l2 contracts**: this question feels like the biggest issue for me on a few levels:
> 1. i can imagine changing the functionality of an nft to a standard factory nft becoming really fraught in a number of ways. two examples that come to mind are soulbound nfts and loanable nfts. neither feature is popular, but it's also not that uncommon to experiment with erc-721 contracts, and permissionless bridging with changed functionality feels like it could be... quite dangerous? i saw in the deck that the concern was malicious contracts; i'd be curious to know more about how that risk could manifest.

Collections that want to preserve special functionality on L2 should deploy a custom ERC721 contract instead of using the standard nft factory. However, there are two main risks with using a custom contract: it could be malicious (e.g. it could implement logic that steals any nft that’s transferred it), or it could be deployed by a trusted party yet have a bug that leads to stolen nfts. Since custom contracts will be necessary for some collections, we think that managing a token list is the best way to solve these issues. That way, nft owners can be sure that the custom contract is safe.
 
> 2. fragmentation across an l2 would also be pretty undesirable—not just for liquidity, but for all kinds of functionality that you might want to build on top of a collection. has there been consideration around consolidating previously bridged nfts after a canonical contract exists?
2. I've written a [tutorial](https://github.com/sam-goldman/optimism-nft-bridge/tree/main/tutorials/l2-custom-erc721) that shows how to resolve this issue :)

**Comment by smartcontracts** [comment] 2022-06-25 00:40
Closing!

**Closed by smartcontracts** 2022-06-25 00:40 UTC
Labels: C-feature-request, M-contracts
