### ISSUE TITLE
Deployer HTTP server stops responding

### ISSUE THREAD

**Issue by TerryHannant** [ethereum-optimism/optimism#957] opened 2021-05-25 21:54 UTC
**Describe the bug**
The HTTP server that is run as part of the Deployer component stops responding to requests after an extended period of time. Unsure of exact period but it appears to be between 4-7 days, after this point all requests for addresses.json/state-dump.latest.json timeout.

**To Reproduce**
1. Clone and build HEAD of develop branch 
2. Start with docker up as per doc
3. Leaving running for at least 4 days 
4. Periodically run curl http://localhost:8080/addresses.json, at some point no response will be received

**Expected behavior**
addresses.json and state-dump.latest.json can be always be retrieved via http on a long running instance

**System Specs:**
 - OS: Debian 10 & Ubuntu 20
 - Package Version (or commit hash): develop branch

**Comment by smartcontracts** [comment] 2021-05-25 23:35
Interesting. I hope there's an easier way to reproduce this than to wait for four days... but I guess I'll try to find a computer that I can do this with.

**Comment by smartcontracts** [comment] 2021-05-25 23:37
Would you mind sharing some context as to why you're running the `deployer` container for 4+ days? If you're just interested in doing local tests you can get around this by `docker-compose down -v` and `docker-compose up` every once in a while I guess. But clearly this is still problematic and we'll take a look at it.

**Comment by smartcontracts** [comment] 2021-05-25 23:45
If you're experiencing this right now, could you run `docker-compose logs --follow deployer` and see if the http server logs anything when you make a request? Can you see any errors in those logs?

**Comment by tynes** [comment] 2021-05-25 23:45
Python Simple HTTP Server is used under the hood to serve the files. Perhaps we can make sure to be using Python3 over Python2 for the file server.

**Comment by smartcontracts** [comment] 2021-05-26 19:35
> The deployer is only long running due to running a full localnet for testing purposes, So restarting it periodic probably would resolve the problem, is it viable to restart just the deployer container without side effect with the rest of the container stack?
> 
> The logs from `ocker-compose logs --follow deployer` show no errors, it only showed last successful request, which was approx 4 days after startup. Subsequent requests 3 days later faileds so thats where the 4-7 day estimate comes from
> 
> Will run a more complete test to see if I can quantify more

Got it. Lack of errors is very weird. Sounds like the http server went down or there's some sort of networking issue. Are you able to get a shell inside the docker container? Maybe you can run `top` to see if the server is still running at all.

**Comment by TerryHannant** [comment] 2021-05-27 06:49
I have since restarted so no longer able to check, will have more detailed look when it happens again. 

To be clear this is has happened every time the containers have been left running for an extended period of time, so the  issue has been observed multiple times

**Comment by smartcontracts** [comment] 2021-05-31 18:34
Honestly we might want to try using a different webserver instead. I'm not sure if SimpleHTTPServer was designed to run for extended periods of time. I'm going to look into alternatives tomorrow.

**Comment by smartcontracts** [comment] 2021-05-31 18:34
Cc @tynes

**Comment by smartcontracts** [comment] 2021-05-31 18:38
Alternatively we could have a script running that will restart the server if it ever stops responding to requests like this. I'm strongly opinionated on "whichever option is easiest" -- not strongly opinionated on which option that actually ends up being.

**Comment by TerryHannant** [comment] 2021-05-31 18:45
I'm pretty sure SImpleHTTP is only meant to be an internal  dev server, so not really surprised at the issue

Should be straight forward to replace it with a simple ngnix setup or such like robust HTTP server

**Comment by tynes** [comment] 2021-06-01 21:24
Serving of `addresses.json` was never really meant to be a long running process, it was just meant to provide the addresses to the various services right after the contracts were deployed. Perhaps you could cache the files locally since they don't change?

**Comment by smartcontracts** [comment] 2021-09-15 21:28
I'm going to close this since the `addresses.json` server was more of a hack than anything and people probably shouldn't be relying on it. If this is a very useful feature to you, please let me know and we can work on specifying a better/more robust way to achieve the same result.

**Closed by smartcontracts** 2021-09-15 21:28 UTC
Labels: C-bug, P-unconfirmed
