### ISSUE TITLE
Downloaded Solidity by hardhat does not have `kall`, causing compilation errors

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/optimism#675] opened 2021-04-28 17:08 UTC
I'm experiencing this issue on [PR 579](https://github.com/ethereum-optimism/optimism/pull/579) / Commit [35cb48d](https://github.com/ethereum-optimism/optimism/commit/35cb48d32d63a838079ae3d9152174b1c394309a). 

### Locally:

1. I check out my branch.
2. It has new dependency ([just OZ contract](https://github.com/ethereum-optimism/optimism/pull/579/files#diff-ebaa48c3dfa5e3d13db1ec0d4053e23f01f6c4fd8e07606f4e426495412300a3R51)) so I run `yarn && yarn build && ` in the root. It works.

### In CI

I see two errors on the [build step](https://github.com/ethereum-optimism/optimism/runs/2457342003?check_suite_focus=true).

First: 
```
lerna ERR! yarn run build stderr:
Error HH503: Couldn't download compiler version 0.7.6. Checksum verification failed. Please check your connection.
For more info go to https://hardhat.org/HH503 or run Hardhat with --show-stack-traces
```

Second:
```
contracts/optimistic-ethereum/libraries/wrappers/Lib_ExecutionManagerWrapper.sol:143:13: DeclarationError: Function not found.
            kall(add(_calldata, 0x20), mload(_calldata), 0x0, 0x0)
            ^--^=
```

**Comment by gakonst** [comment] 2021-04-28 18:04
Not sure why you're getting the `kall` error, maybe @ben-chain knows? The checksum verification error is a weird one, maybe related to https://github.com/nomiclabs/hardhat/issues/1332#issuecomment-818212424? Can you try rebasing your branch to master? We recently updated hardhat.

**Comment by TransmissionsDev** [comment] 2021-04-28 19:25
I'm seeing that error locally as well!

**Comment by snario** [comment] 2021-04-28 19:48
I've seen this recently too and have downloaded the logs from a failing CI run for the developer tackling this issue to use for debugging purposes:
[logs_5044.zip](https://github.com/ethereum-optimism/optimism/files/6394391/logs_5044.zip)

**Comment by TransmissionsDev** [comment] 2021-04-28 19:50
Can this be P-high? Literally cannot test locally rn.

**Comment by snario** [comment] 2021-04-28 20:43
Fixed in https://github.com/ethereum-optimism/optimism/pull/668

**Comment by TransmissionsDev** [comment] 2021-04-28 22:02
Still seeing this issue after pulling from main

**Comment by snario** [comment] 2021-04-28 23:36
Hm. Re-opening and renaming.

**Comment by gakonst** [comment] 2021-04-30 14:26
I think this error happens because it tries to use the EVM Compiler (0.7.6) instead of the OVM compiler.

**Comment by TransmissionsDev** [comment] 2021-04-30 16:00
> I think this error happens because it tries to use the EVM Compiler (0.7.6) instead of the OVM compiler. It makes sense that `kall` would not be found if so.

Seems like it.

The logs show

```
#29 42.50 $ ./scripts/build.sh
#29 42.50 $ tsc -p ./tsconfig.build.json
#29 42.50 $ hardhat compile --show-stack-traces
#29 42.50 Compiling 97 files with 0.7.6
```

**Comment by TransmissionsDev** [comment] 2021-04-30 16:18
The build script runs `yarn compile:contracts`? That is probably the cause of the error right? Need it to ignore OVM contracts?

<img width="977" alt="Screen Shot 2021-04-30 at 9 17 09 AM" src="https://user-images.githubusercontent.com/26209401/116723921-dba1cc80-a994-11eb-85da-2c052fab95c5.png">

**Comment by ben-chain** [comment] 2021-04-30 19:49
I have been looking into this for the past day and it's really stumping me, really sorry for the interruption to service @TransmissionsDev !  To confirm -- are you still getting this in the monorepo?  If it's only on your local dev environment, can you try putting [this version](https://github.com/ethereum-optimism/optimism/blob/4837aaed3fe10ea515c3bc6685d506a13b382f8e/packages/contracts/hardhat.config.ts#L56) into your `hardhat.config.ts` and tell me if it goes away?

**Comment by TransmissionsDev** [comment] 2021-04-30 20:05
> I have been looking into this for the past day and it's really stumping me, really sorry for the interruption to service @TransmissionsDev ! To confirm -- are you still getting this in the monorepo? If it's only on your local dev environment, can you try putting [this version](https://github.com/ethereum-optimism/optimism/blob/4837aaed3fe10ea515c3bc6685d506a13b382f8e/packages/contracts/hardhat.config.ts#L56) into your `hardhat.config.ts` and tell me if it goes away?

Yep still getting this. Already have that version in my `hardhat.config.ts`.

The weirdest part is that if I run ./scripts/build.sh myself I don't see this problem. But if immediately after I try to run `docker-compose up` in `ops` I continue to see the same error.

**Comment by TransmissionsDev** [comment] 2021-04-30 20:12
Could this be related to my docker-compose and docker versions?

What versions do you guys use?

**Comment by ben-chain** [comment] 2021-04-30 20:31
Hmmm, I'm on the same versions.  Would you be able to try a `docker system prune` or something of the sort?  This feels like it may be a cached version being held on in docker that is not up to date with `solc-bin`

**Comment by ben-chain** [comment] 2021-04-30 21:40
@TransmissionsDev I am pretty sure at this point that this is a caching issue with the docker build.  Specifically, we have local logic which checks if the `soljson.js` has been changed in the hardhat compiler.  However, `docker build` will bypass this if it does not see changes to the filesystem.  So, if you delete all the images where this build might be cached, forcing the OVM compiler to be downloaded, I think this should go away. 🤞

**Comment by smartcontracts** [comment] 2021-05-01 00:20
@TransmissionsDev plz try nuking the monorepo if you can do that without losing any work. We added cache invalidation in a recent version of `hardhat-ovm` that will probably solve this. If still doesn't work after doing that, lemme know.

**Comment by snario** [comment] 2021-05-01 00:25
In particular, ensure you rebuild the (untagged) `builder` image.

**Comment by TransmissionsDev** [comment] 2021-05-01 00:28
Will give this a shot rn. I tried nuking (rm -rf) and running `docker system prune -a` earlier but that broke even more stuff lmao, going to try restarting my laptop too.

**Comment by TransmissionsDev** [comment] 2021-05-01 02:41
Wtf lol

Nuking and pruning now breaks the builder, dtl, batch_submitter and relayer.

https://gist.github.com/TransmissionsDev/18a87aa62f4ff4e9461505484ae0588f

**Comment by TransmissionsDev** [comment] 2021-05-01 02:50
Here's me trying to build again: 

https://gist.github.com/TransmissionsDev/97aad46dec69dbf3a864774367a15c0d

**Comment by bscarano** [comment] 2021-05-01 09:34
Unfortunately nuking and rebuilding still results in the same error with `kall` not found.

**Comment by platocrat** [comment] 2021-05-03 19:00
I can confirm that Ale from Synthetix also experiences this same error when attempting to run `docker-compose build` locally.

**Comment by ben-chain** [comment] 2021-05-03 20:21
Hmmm, the compiler is absolutely updated by now, so this must be a caching issue where the old version is being held on to by docker.  @TransmissionsDev have you tried `docker-compose build --no-cache` since https://github.com/ethereum-optimism/optimism/pull/723 was merged?

**Comment by TransmissionsDev** [comment] 2021-05-03 20:44
> Hmmm, the compiler is absolutely updated by now, so this must be a caching issue where the old version is being held on to by docker. @TransmissionsDev have you tried `docker-compose build --no-cache` since #723 was merged?

Yep even did a full `docker system prune -a` :(

**Comment by TransmissionsDev** [comment] 2021-05-03 20:47
I can give you guys remote access to my laptop and you could try debugging that way? 😂

**Comment by gakonst** [comment] 2021-05-03 21:49
Is this an M1 issue?

**Comment by platocrat** [comment] 2021-05-03 22:10
> Is this an M1 issue?

that's some great intuition. Hadn't thought of that but it's possible.

**Comment by ben-chain** [comment] 2021-05-03 22:21
I have a fresh M1 that I will go try this out on now.  I'm not sure if it'll be possible to replicate as it is almost certainly a caching issue, and I probably missed the window to have my machine cache the wrong thing, but worth a shot.  I'm really stumped by this.  We may need to just move to a new compiler version string which has not been used previously to get it working.

**Comment by ben-chain** [comment] 2021-05-03 22:22
@bscarano if you get a chance, would you mind sharing if you are on an M1, and if `--no-cache` solves this for you? :)

**Comment by platocrat** [comment] 2021-05-03 22:40
@gakonst @ben-chain  confirmed with Ale from Synthetix that it's an issue on M1 macs only.
He tried his same setup on his old Intel mac and it worked

**Comment by ben-chain** [comment] 2021-05-03 22:47
Great news--and better yet, I was just able to replicate this on my own M1, so should be much easier to fix now that I can see it in front of me!

**Comment by TransmissionsDev** [comment] 2021-05-03 23:16
> Great news--and better yet, I was just able to replicate this on my own M1, so should be much easier to fix now that I can see it in front of me!

Woohoo!!

**Comment by bscarano** [comment] 2021-05-03 23:17
> @bscarano if you get a chance, would you mind sharing if you are on an M1, and if `--no-cache` solves this for you? :)

Yes I have an M1!

**Comment by smartcontracts** [comment] 2021-05-03 23:47
General FYI to anyone working on this issue, our compiler caching logic within `@eth-optimism/hardhat-ovm` happens here: https://github.com/ethereum-optimism/optimism/blob/master/packages/hardhat-ovm/src/index.ts#L38-L105.

**Comment by ben-chain** [comment] 2021-05-04 05:20
@smartcontracts and I spent a bunch more time narrowing in on the root of this issue and finally found it.  It turns out it is related to how hardhat tasks behave on M1 docker--it is running a different task than the `hardhat-ovm` plugin is hooked into.  So what's really happening is the `hardhat-ovm` compiler plugin just isn't being activated on M1s--it is really just hardhat running the vanilla compiler on the `unsupported: evm` contracts.

We only have a partial fix so far, but I can now run the system on my M1 if I serve the predeploys locally!  [Here's a branch](https://github.com/ben-chain/optimism/tree/fix/HH-OVM-M1) with the fix and required env change.  If I `yarn build:dump && yarn serve` in the contracts then I can get things running with that.

Here was [the diff](https://github.com/ben-chain/optimism/commit/63c57376e0e059752218db6f6701442717b4c669) that gets builds partially working.  I exec'd into the `deployer` and it looks like there are some missing `ovm-artifacts`, backed up by [this CI run](https://github.com/ben-chain/optimism/pull/3/checks?check_run_id=2497474221#step:9:325).  Getting close!

**Comment by bscarano** [comment] 2021-05-04 11:40
Confirmed that applying the changes from [@ben-chain's branch](https://github.com/ben-chain/optimism/tree/fix/HH-OVM-M1) resolves the issue with `docker-compose build` and the OVM compiler. 🙏

The workaround of serving the contracts locally i'm seeing a mix of success/failure. I see many errors connecting from the container to 8081:

```
dtl_1                | curl: (7) Failed to connect to deployer port 8081: Connection refused
batch_submitter_1    | curl: (7) Failed to connect to deployer port 8081: Connection refused
l2geth_1             | curl: (7) Failed to connect to deployer port 8081: Connection refused
eth_chainId (3)      | curl: (7) Failed to connect to deployer port 8081: Connection refused
```

But I also see:
`l2geth_1             | INFO [05-04|11:32:06.734] Fetching state dump                      path=http://host.docker.internal:8081/state-dump.latest.json`

succeed with a 200 to the local server.

**Comment by ben-chain** [comment] 2021-05-04 17:26
@bscarano Would you be able to share the full logs here? :)

**Closed** 2021-05-05 01:34 UTC
Labels: C-bug, C-meta

**Comment by alcuadrado** [comment] 2021-05-05 14:38
Hey, @gakonst pointed us to this issue. Can someone help me reproduce it? I tried replicating some of the CI runs locally, but I think those commits are no longer available. I have an M1, so it should be doable.

**Comment by alcuadrado** [comment] 2021-05-05 15:53
I got to reproduce it going to `master` and removing a few commits. 

What's happening is that when using an M1 Mac your docker images are arm-base, and there are no arm solc builds, so only solcjs is used. 

To validate this I just `exec`'ed and printed `uname -a` from `packages/contracts/hardhat.config.ts`, which results in `Linux buildkitsandbox 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 GNU/Linux`

**Comment by gakonst** [comment] 2021-05-06 08:59
Thanks a ton for the help @alcuadrado. @ben-chain ^ FYI.
