### ISSUE TITLE
Blocknumber monotonicity violation on 0.5.6

### ISSUE THREAD

**Issue by yorickdowne** [ethereum-optimism/optimism#2033] opened 2022-01-19 19:42 UTC
**Describe the bug**

Updated a synced 0.5.5 replica to l2geth 0.5.6. With every new block, I'd see `Blocknumber monotonicity violation`.

Dropping it back down to 0.5.5 resolved the error messages.

I can likely reproduce this at will: Let me know what is useful to you to track down root cause.

**Comment by tynes** [comment] 2022-01-19 23:41
Thanks for the report. I believe it is fixed in https://github.com/ethereum-optimism/optimism/pull/2040 but I need to reproduce it locally to be sure. I believe that its falsely reporting that there is a monotonicity error due to the branching logic before the logline.

**Closed** 2022-01-21 18:51 UTC
Labels: C-bug, C-customer-issue, M-l2geth
