### ISSUE TITLE
Behaviour of `block.number` on `eth_call` is incorrect

### ISSUE THREAD

**Issue by guanzhenxing** [ethereum-optimism/optimism#530] opened 2021-04-21 03:20 UTC
**Problem:** When using `block.number` in Solidity code, sometimes it uses the blockNumber of L1 and sometimes it uses the blockNumber of L2. (See screenshot and code for detailed instructions).

**Requirement:** What exactly is the behaviour of `block.number`? How to ensure that it always returns the L1 or L2 blockNumber in the contract.

This is my test code: https://github.com/guanzhenxing/optimism-test

And I run my code.Get the result like this:

![image](https://user-images.githubusercontent.com/3087325/115491716-1029d000-a293-11eb-8939-3f81c6e9c166.png)
A red underline indicates that block.number has not been changed. A green underline means that I called the method that changed blockNumber.

And in my project code, the difference between BlockNumberTest1.sol and BlockNumberTest.sol is the `compareAndUpdateUserState()` method.
When running ` require(state.blockNumber <= blockNumber, "state.blockNumber must be smaller or equal to blockNumber") first; ` it gives an error, but running ` updateUserState()` is fine.

**Comment by garyng2000** [comment] 2021-04-21 03:54
the problem is deeper that this, block.blockNumber inside the sol is referring to L1#, not L2. is that intended ?

**Comment by gakonst** [comment] 2021-04-21 08:34
I don't understand what the issue is, could you please give some more context on:
1. What you want to do
2. What you expected to get
3. What you actually got
4. What you think the issue is?

**Comment by guanzhenxing** [comment] 2021-04-21 08:46
> I don't understand what the issue is, could you please give some more context on:
> 
> 1. What you want to do
> 2. What you expected to get
> 3. What you actually got
> 4. What you think the issue is?

Thank you! I have added some descriptions to the question.

**Comment by guanzhenxing** [comment] 2021-04-21 08:46
Thank you! I have added some descriptions to the question. @gakonst

**Comment by tynes** [comment] 2021-04-21 16:19
> What exactly is the behaviour of block.number? How to ensure that it always returns the L1 or L2 blockNumber in the contract.

`block.number` is updated after a L1 to L2 transaction or the sequencer may update it over time as long as it is monotonic.
See for more detail: https://github.com/ethereum-optimism/optimism/pull/531

> When using block.number in Solidity code, sometimes it uses the blockNumber of L1 and sometimes it uses the blockNumber of L2. (See screenshot and code for detailed instructions).

Could you elaborate more? I don't follow what you mean

**Comment by garyng2000** [comment] 2021-04-21 16:45
when executing a pure function, block.number returns L2#. When executing a transaction(i.e. need to go to L1) the block# is the L1 one but that is not predictable so it could be 50 transactions all sharing the same L1 block#  even separated by 20 minutes

**Comment by tynes** [comment] 2021-04-22 00:02
> when executing a pure function, block.number returns L2#.

Do you mean an `eth_call` returns the L2 height while a transaction has the correct set by L1 height?

Tests for `NUMBER` are here
https://github.com/ethereum-optimism/optimism/blob/7e9ca1eb2d1e1665539eaeadfb573a768bb6f601/integration-tests/test/ovmcontext.spec.ts#L65

Note that the `eth_call` for `block.number` test at the bottom is broken for what I believed to be a different reason, fixed in https://github.com/ethereum-optimism/optimism/pull/477. Its possible that there are 2 bugs here and I'm only aware of one of them

**Comment by garyng2000** [comment] 2021-04-22 07:55
I am not sure what the test is intended for but I can tell for sure pure sol function return L2 block height(number), transaction return L1 block height(but this seems to be the last 'sync' one, not when it is actually executed on L1). 

I can understand why pure function may not be the same(this is even true on ethereum as when the transaction is included is unknown). It is the unpredictable block# for transaction that is the issue. there is no 'time' anymore. ethereum may not have an 'accurate time' but a reasonably correct ballpark. optimism has none

**Comment by platocrat** [comment] 2021-04-25 20:22
@guanzhenxing and @tynes do you two have any updates on this issue?

**Comment by guanzhenxing** [comment] 2021-04-26 02:25
I feel that I cannot do something about block.number and we are looking at the option of whether we can use timestamp in the contract of the loan protocol.
@platocrat

**Closed** 2021-04-26 19:44 UTC
Labels: C-bug, C-question, P-unconfirmed

**Comment by tynes** [comment] 2021-04-26 20:01
@guanzhenxing This has been fixed in #632, please feel to reopen if you experience any more issues

**Comment by guanzhenxing** [comment] 2021-05-07 03:29
@tynes I tested it and found that the `block.number` is the same for several transactions. Is this Issue the only way to go?
