### ISSUE TITLE
Verifier cannot sync transaction batches to tip

### ISSUE THREAD

**Issue by gabronick** [ethereum-optimism/optimism#3646] opened 2022-10-04 10:36 UTC
**Describe the bug**

node stops at block 2093461

**To Reproduce**
1. Configure the node using: https://community.optimism.io/docs/developers/build/run-a-node/#install-packages
2. Synchronize node using L1 (ETH archive nodes)

DTL .env file:

-----------------------------------------------------------------------
```
# General options
DATA_TRANSPORT_LAYER__NODE_ENV=production
# Leave blank during local development
DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME=mainnet
DATA_TRANSPORT_LAYER__DB_PATH=/external/dtl/db
DATA_TRANSPORT_LAYER__ADDRESS_MANAGER=0xdE1FCfB0851916CA5101820A69b13a4E276bd81F
DATA_TRANSPORT_LAYER__POLLING_INTERVAL=5000
DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS=true
DATA_TRANSPORT_LAYER__CONFIRMATIONS=12

# Server options
DATA_TRANSPORT_LAYER__SERVER_HOSTNAME=localhost
DATA_TRANSPORT_LAYER__SERVER_PORT=7878

# Set to "true" if you want to sync confirmed transactions from L1 (Ethereum).
# You probably want to set this to "true".
DATA_TRANSPORT_LAYER__SYNC_FROM_L1=true
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=XXXXXX:8545
DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL=500

# Set to "true" if you want to sync unconfirmed transactions from a sequencer.
# Make sure to fill in the below values if you intend to do so.
DATA_TRANSPORT_LAYER__SYNC_FROM_L2=false
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL=1000
DATA_TRANSPORT_LAYER__L2_CHAIN_ID=10
DATA_TRANSPORT_LAYER__LEGACY_SEQUENCER_COMPATIBILITY=false

DATA_TRANSPORT_LAYER__L1_START_HEIGHT=13596466

# Monitoring
# Leave the SENTRY_DSN variable unset during local development
DATA_TRANSPORT_LAYER__USE_SENTRY=
DATA_TRANSPORT_LAYER__SENTRY_DSN=
DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE=

DATA_TRANSPORT_LAYER__ENABLE_METRICS=
```

--------------------------------------------------------------

L2GETH runner (same envs config)

-----------------------------

```
[Service] 
Environment="CHAIN_ID=10"
Environment="DATADIR=/external/gethData"
Environment="NETWORK_ID=10"
Environment="NO_DISCOVER=true"
Environment="NO_USB=true"
Environment="GASPRICE=0"
Environment="GCMODE=archive"
Environment="BLOCK_SIGNER_ADDRESS=0x00000398232E2064F896018496b4b44b3D62751F"
Environment="BLOCK_SIGNER_PRIVATE_KEY=6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
Environment="ETH1_CTC_DEPLOYMENT_HEIGHT=13596466"
Environment="ETH1_SYNC_SERVICE_ENABLE=true"
Environment="ROLLUP_ADDRESS_MANAGER_OWNER_ADDRESS=0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A"
Environment="ROLLUP_CLIENT_HTTP=http://localhost:7878"
Environment="ROLLUP_DISABLE_TRANSFERS=false"
Environment="ROLLUP_ENABLE_L2_GAS_POLLING=false"
Environment="ROLLUP_GAS_PRICE_ORACLE_OWNER_ADDRESS=0x648E3e8101BFaB7bf5997Bd007Fb473786019159"
Environment="ROLLUP_MAX_CALLDATA_SIZE=40000"
Environment="ROLLUP_POLL_INTERVAL_FLAG=1s"
Environment="ROLLUP_SYNC_SERVICE_ENABLE=true"
Environment="ROLLUP_TIMESTAMP_REFRESH=5m"
Environment="ROLLUP_VERIFIER_ENABLE=true"
Environment="RPC_ADDR=0.0.0.0"
Environment="RPC_API=eth,rollup,net,web3,debug"
Environment="RPC_CORS_DOMAIN=*"
Environment="RPC_ENABLE=true"
Environment="RPC_PORT=8545"
Environment="RPC_VHOSTS=*"
Environment="TARGET_GAS_LIMIT=15000000"
Environment="USING_OVM=true"
Environment="WS_ADDR=0.0.0.0"
Environment="WS_API=eth,rollup,net,web3,debug"
Environment="WS_ORIGINS=*"
Environment="WS=true"
Environment="ROLLUP_BACKEND=l1"

User=ubuntu 
Group=ubuntu 
Restart=on-failure 
RestartSec=5s 
ExecStart=/external/optimism/l2geth/build/bin/geth --nousb --datadir=/external/gethData --password=/external/password -allow-insecure-unlock --unlock=0x00000398232E2064F896018496b4b44b3D62751F --mine --miner.etherbase=0x00000398232E2064F896018496b4b44b3D62751F

[Install] 
WantedBy=default.target
```
----------------------------------------------------------------

**Expected behavior**

the node should keep syncing

**Screenshots**

![image](https://user-images.githubusercontent.com/54854657/193798037-2de6d8d9-8660-4ac4-9978-b897bf75b90c.png)

**System Specs:**
 - OS: Ubuntu 22.04 ARM64
 - Package Version (or commit hash):   302700d694ad448befadc23760a9e5b448e3754d

**Additional context**

**Comment by smartcontracts** [comment] 2022-10-18 18:05
Closing as duplicate of #3693

**Closed by smartcontracts** 2022-10-18 18:05 UTC
