### ISSUE TITLE
Clone succeeded, but checkout failed.

### ISSUE THREAD

**Issue by niklr** [ethereum-optimism/optimism#647] opened 2021-04-27 13:38 UTC
Probably just an issue on Windows:

Cloning into 'G:\Projects\GitHub\optimism'...
remote: Enumerating objects: 10899, done.        
remote: Counting objects: 100% (10850/10850), done.        
remote: Compressing objects: 100% (4603/4603), done.        
remote: Total 10899 (delta 5565), reused 10374 (delta 5286), pack-reused 49        
Receiving objects: 100% (10899/10899), 13.92 MiB | 4.52 MiB/s, done.
Resolving deltas: 100% (5566/5566), done.
error: invalid path 'packages/contracts/deployments/goerli-v1/OVM_ChainStorageContainer:CTC:batches.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by smartcontracts** [comment] 2021-04-27 20:26
Related to: https://github.com/ethereum-optimism/optimism/issues/558

We need to change these file names ASAP.

**Comment by snario** [comment] 2021-04-27 21:45
Yeah this is a dupe of #558. Closing. Windows is not massive priority for us right now but the solution is rather straightforward (i.e., rename those files). If anyone seeing this would like to contribute to the project we'd welcome a PR to to fix #558!

**Closed by snario** 2021-04-27 21:45 UTC
Labels: A-ci, A-contracts, C-bug

**Comment by joshstevens19** [comment] 2021-04-27 21:59
I understand it’s not priority but just so you know some windows versions do not support window for linux these people would be stuck not being able to deploy anything. We have someone at work in that exact situation who is the game developer meaning we had to create a GitHub action for him to deploy it. Meaning his flow is push to master then deploy then test and repeat. I personally would raise this as a higher priority if possible and as you said seems a very easy fix. Just my POV. Thanks
