### ISSUE TITLE
Identical transaction executed several times on mainnet

### ISSUE THREAD

**Issue by fdemiramon** [ethereum-optimism/optimism#2500] opened 2022-04-27 16:39 UTC
**Describe the bug**
The same transaction has been executed at least 3 times on the mainnet

**To Reproduce**
See that the transaction `0x9ed8f713b2cc6439657db52dcd2fdb9cc944915428f3c6e2a7703e242b259cb9` exists in at least 3 different blocks in the blockchain:
* https://optimistic.etherscan.io/tx/985
* https://optimistic.etherscan.io/tx/19022
* https://optimistic.etherscan.io/tx/45036

Funny to see that the transaction hash in Etherscan has been manipulated and the hash of the second and third transactions are prefixed with `DUPE2` and `DUPE3`.

**Expected behavior**
An identical transaction cannot be executed several times, because the sender address's nonce cannot be reused.
So, the second and third transaction could have not been executed in a normal conditions.

**Screenshots**
<img width="982" alt="image" src="https://user-images.githubusercontent.com/5026039/165573513-b36e4359-d6df-463a-8e32-c3c26000910a.png">
<img width="937" alt="image" src="https://user-images.githubusercontent.com/5026039/165573321-94acbc33-c8e6-4b6c-a7f0-49d2317fb6a2.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/5026039/165572783-3d7d45f0-1bb4-4fa9-9626-fe43016bd03d.png">

**System Specs:**
 - OS: n/A
 - Package Version (or commit hash): n/a

**Comment by smartcontracts** [comment] 2022-04-27 16:47
Duplicate of https://github.com/ethereum-optimism/optimism/issues/2010

This was the result of an early whitelisting bug. We have not yet attempted to fix the issue. Are you running a service that's not working as a result of this bug?

**Comment by smartcontracts** [comment] 2022-05-04 18:12
Closing as duplicate of #2010, if this is causing an issue for you please leave a comment on #2010.

**Closed by smartcontracts** 2022-05-04 18:12 UTC
