### ISSUE TITLE
Potential bug with nonce check within preCheck

### ISSUE THREAD

**Issue by mask-pp** [ethereum-optimism/optimism#1923] opened 2021-12-14 06:45 UTC
If this [line](https://github.com/ethereum-optimism/optimism/blob/2b7436788e6998cddbeaae4beac4137047f0efff/l2geth/core/state_transition.go#L216) is executed, then it means that a too-high nonce check is invalid

**Comment by smartcontracts** [comment] 2021-12-15 16:29
This is a special condition within the `preCheck` function because L1 => L2 transactions have a nonce but do not increment the nonce of the account that appears to be sending the transaction (I think the nonce is the position of the L1 => L2 transaction within the queue of these transactions back on L1). We may change this behavior as part of the next major upgrade.

**Comment by smartcontracts** [comment] 2022-02-09 15:40
Closing as this is not a bug in the current system

**Closed by smartcontracts** 2022-02-09 15:40 UTC
Labels: C-bug, P-unconfirmed, M-l2geth
