### ISSUE TITLE
CrossChainMessenger: Support multiple withdrawals

### ISSUE THREAD

**Issue by nicholaspai** [ethereum-optimism/optimism#5983] opened 2023-06-10 12:24 UTC
**Describe the bug**
The CrossChainMessenger is [known to not support multiple withdrawals](https://github.com/ethereum-optimism/optimism/blob/develop/packages/sdk/src/cross-chain-messenger.ts#L432). This creates a problem for use cases like Bridges that often do have these sorts of L2 transactions containing multiple withdrawals.

**To Reproduce**
Example [L2 txn](https://optimistic.etherscan.io/tx/0xd73f0cdf499830f2919f3009cee35611abf5a01842c4eed0e8c2493a00969a5b)

**Expected behavior**
```
Error: multiple withdrawals found in receipt
    at CrossChainMessenger.toLowLevelMessage (/Users/nicholaspai/UMA/relayer-v2/node_modules/@eth-optimism/sdk/src/cross-chain-messenger.ts:439:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CrossChainMessenger.getMessageStatus (/Users/nicholaspai/UMA/relayer-v2/node_modules/@eth-optimism/sdk/src/cross-chain-messenger.ts:668:30)
```

**System Specs:**
 - Package Version (or commit hash): `"@eth-optimism/sdk": "^2.1.0"`

**Comment by annieke** [comment] 2023-06-12 20:03
hi, we're aware of this issue and are looking to ship a fix in ~a week! thank you for the report

**Comment by roninjin10** [comment] 2023-06-13 13:54
> [](https://github.com/across-protocol/optimism/commit/2bbdb4dc69d8b563b14fdc498f68ef9e71dc71e1#diff-77164cc5c071d1488e1cf72c0f91fdd99dd8976edb5004c83198bbd517039572)

This would work but we will get something clean out for ya'll

**Comment by nicholaspai** [comment] 2023-06-14 19:49
> > 
> 
> This would work but we will get something clean out for ya'll

cc @annieke it also seems there is an additional bug that finalized withdrawals are not getting marked with the correct `RELAYED` status

I've been able to manually finalize withdrawals locally but I don't see the status updated

Example L2 withdrawal:
- https://optimistic.etherscan.io/tx/0xda9e9c8dfc7718bc1499e1e64d8df6cddbabc46e819475a6c755db286a41b9fa

L1 finalization: 
- https://etherscan.io/tx/0x9bc7b3a1056d4a2829ea253e290877fb25d61f07153b638767d2bb8d44e520d3

Perhaps because these are pre-bedrock?

**Comment by roninjin10** [comment] 2023-06-15 18:10
Hey @nicholaspai, small update.   Based on my investigation of the SDK the "cleaner solution" I was hoping to do is a little too risky of a refactor to do as it might cause regressions.   I am currently going with the idea you suggested where you would pass in a `withdrawaIndex`.   By using `populateTransaction` you would be able to aggregate them into a multicall.   The work is being done in this pr https://github.com/ethereum-optimism/optimism/pull/6024 and should be released soon

**Comment by roninjin10** [comment] 2023-06-15 18:11
@nicholaspai regarding the finalization issue you mentioned, prebedrock withdrawals are getting correct message status in our production code atm.    I will test it out myself to try to repro with the withdrawal you shared

**Comment by nicholaspai** [comment] 2023-06-15 18:12
> Hey @nicholaspai, small update. Based on my investigation of the SDK the "cleaner solution" I was hoping to do is a little too risky of a refactor to do as it might cause regressions. I am currently going with the idea you suggested where you would pass in a `withdrawaIndex`. By using `populateTransaction` you would be able to aggregate them into a multicall. The work is being done in this pr #6024 and should be released soon

Nice thanks. Curious what do you think of the `MESSAGE_STATUS` bug I think exists ([comment](https://github.com/ethereum-optimism/optimism/issues/5983#issuecomment-1591880321) for pre Bedrock withdrawals?

It's a bit annoying to have to fix since these withdrawals shouldn't grow over time but there might be some other dApps/deves who run into that bug? We were able to manually withdraw the pre bedrock withdrawals and added some logic to just ignore those withdrawals.

**Comment by roninjin10** [comment] 2023-06-15 18:37
Yea we will have to repro because all of our legacy withdrawals are working.    My only guess is that it requires the combination of being both a multicall and a legacy withdrawal to repro but I will try to repro today

**Comment by nicholaspai** [comment] 2023-06-15 19:02
> Yea we will have to repro because all of our legacy withdrawals are working. My only guess is that it requires the combination of being both a multicall and a legacy withdrawal to repro but I will try to repro today

oh yeah the legacy withdrawal works, the status is just not set correctly from `READY_TO_RELAY` to `RELAYED`

**Comment by roninjin10** [comment] 2023-06-15 21:18
Right on our end this sdk method is returning RELAYED correctly

**Comment by roninjin10** [comment] 2023-06-16 07:03
@nicholaspai thanks for the second report!  I have reproed on your withdrawals but also on testnet.   This is a regression.  You were correct and I was wrong because this issue affects ALL historical withdrawals.  We'll get a fix in for both issues in asap.

**Comment by roninjin10** [comment] 2023-06-17 02:14
hey @nicholaspai, I got both fixes in. So you don't have to wait for our normal release you can `npm install @eth-optimism/sdk@0.0.0-20230617021031` to use the version of the sdk with the fixes in it right away.  We should have an official release sometime next week.

Have a great weekend!

**Comment by nicholaspai** [comment] 2023-06-19 13:51
> hey @nicholaspai, I got both fixes in. So you don't have to wait for our normal release you can `npm install @eth-optimism/sdk@0.0.0-20230617021031` to use the version of the sdk with the fixes in it right away. We should have an official release sometime next week.
> 
> Have a great weekend!

thanks! We'll just wait for the normal release as we're running successfully on a fork of the `eth-optimism/sdk` for now

**Comment by annieke** [comment] 2023-06-21 00:12
Resolved by this tag: https://github.com/ethereum-optimism/optimism/releases/tag/%40eth-optimism%2Fsdk%403.0.0

**Comment by annieke** [comment] 2023-06-21 21:55
Oops, should be tracking this PR https://github.com/ethereum-optimism/optimism/pull/6053 instead; reopening!

**Closed** 2023-06-29 23:41 UTC
Labels: C-feature-request, M-sdk

**Comment by ahyammona** [comment] 2024-04-11 07:07
Error: withdrawal index 0 out of bounds. There are 0 withdrawals this is waht i get
