### ISSUE TITLE
Bug:  `ops` tool does not build on a user's Intel Mac 

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/optimism#1311] opened 2021-08-04 13:42 UTC
This bug was surfaced by @nicholaspai

**Describe the bug**
@nicholaspai runs an Intel Mac and is experiencing an error when attempting to start the docker containers from the `ops` tool.

**To Reproduce**
1. Git clone monorepo:  `git clone https://github.com/ethereum-optimism/optimism.git`
2. `yarn && yarn build`
3. `cd ops && docker-compose build && docker-compose up`
4. See error:
```
panic: runtime error: index out of range [0] with length 0

goroutine 78 [running]:
github.com/docker/compose-cli/pkg/compose.(*convergence).updateProject(0xc00000d098, 0xc000262460, 0xc0000c8e40, 0xa)
    github.com/docker/compose-cli/pkg/compose/convergence.go:114 +0xfcf
github.com/docker/compose-cli/pkg/compose.(*convergence).apply.func1(0x20d6548, 0xc0005670e0, 0xc0000c8e40, 0xa, 0x1f2d4e5, 0x8)
    github.com/docker/compose-cli/pkg/compose/convergence.go:104 +0x292
github.com/docker/compose-cli/pkg/compose.run.func1(0x0, 0x0)
    github.com/docker/compose-cli/pkg/compose/dependencies.go:102 +0xa3
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000255aa0, 0xc000466600)
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Expected behavior**
Since I also run an Intel Mac and experienced no issues when following the repro steps above, we expect for there to be no issues when starting/running the docker containers in the `ops` tool.

**System Specs:**
 - OS: Intel Mac

**Additional context**
[Link to the first error of the discussion on Discord](https://discord.com/channels/667044843901681675/676980316518481930/872193638069837835)

**Comment by nicholaspai** [comment] 2021-08-04 13:44
Thanks @platocrat ! Small correction:

> After advising him to clear his docker cache with docker system prune -a, he now experiences the error shown below in the repro steps.

I  ran the reproduction steps and actually just saw the same error originally described `panic: runtime error: index out of range [0] with length 0`.

**Comment by platocrat** [comment] 2021-08-04 13:46
> Thanks @platocrat ! Small correction:
> 
> > After advising him to clear his docker cache with docker system prune -a, he now experiences the error shown below in the repro steps.
> 
> I ran the reproduction steps and actually just saw the same error originally described `panic: runtime error: index out of range [0] with length 0`.

I apologize for the mistake. Updated the issue to reference only first error :)

**Comment by smartcontracts** [comment] 2021-11-04 19:42
We really need to dedicate some time to fixing any docker issues with macos. Luckily, most people won't have to run the `ops` setup anymore after OVM 2.0.

**Comment by smartcontracts** [comment] 2022-03-25 22:03
Hmmm this issue is really old, I'm gonna try building on my Intel Mac and see if I can still reproduce. If I can't reproduce, I'm probably just gonna close this issue and we can either re-open or create a new issue if someone else runs into the same problem down the line.

**Comment by smartcontracts** [comment] 2022-03-27 17:05
I was able to build fine on my intel mac. Going to close this issue. If someone else runs into this issue again in the future, we can re-open.

**Closed by smartcontracts** 2022-03-27 17:05 UTC
Labels: C-bug, M-ops, P-unconfirmed
