### ISSUE TITLE
Using `optimism` repo as a submodule results in docker related errors

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/optimism#493] opened 2021-04-19 18:30 UTC
**Describe the bug**
If the `optimism` repo is used as a submodule to another project, this results in `docker-compose` errors. The exact problem has not been found, but it appeared to be related to problems with the internal network. The services were not being initialized with the dynamic environment variables, in particular the `ADDRESS_MANAGER_ADDRESS`

**To Reproduce**
1. Add this repo to another repo as a submodule and pull/update
1. Start up the `docker-compose` service from within the submodule
1. The services will not properly start

**Expected behavior**
I don't think using this repo as a submodule should break the docker setup - devs need a way to develop their apps against the system. This is meant to save time for future devs who attempt to use this repo as a submodule

**Additional context**
It would be nice if we could release an `npm` package that was a CLI tool that wraps `docker-compose` so that devs could install that package as part of their project and `npx run optimism start` or something like that

**Comment by snario** [comment] 2021-04-19 18:44
What is the use case motivating the use of this repository as a submodule? cc @TransmissionsDev

**Comment by TransmissionsDev** [comment] 2021-04-19 21:50
> What is the use case motivating the use of this repository as a submodule? cc @TransmissionsDev 

Making it easier to clone and get started. But pretty easy to just write a bash script that does the install in a parent directory instead so not critical.

**Comment by TransmissionsDev** [comment] 2021-04-19 21:51
A wrapper around docker compose that could be run with npx sounds awesome and would bypass the need to make submodules work.

**Comment by snario** [comment] 2021-04-19 23:39
Thanks @TransmissionsDev, I'm still a bit confused at the motivation. Assuming that using the monorepo as a submodule is so that you can make modifications to the repository while developing on top of it?

Could you share the bash script, or how you're using `npm` scripts to programmatically run a local development environment?

Also curious why you need to entire system to be running?

Finally, you could also create your own copy of the `docker-compose.yml` except without using build contexts as directories, and just using the base `image` pulled from Docker Hub.

**Comment by snario** [comment] 2021-04-19 23:39
Also finally could you share any logs from the issue that get shown when you run this locally?

**Comment by TransmissionsDev** [comment] 2021-04-19 23:59
>  Assuming that using the monorepo as a submodule is so that you can make modifications to the repository while developing on top of it?

Nah just meant that since its a submodule it gets cloned with the repo and then you can have npm scripts that start up the containers along with running tests. 

> Also curious why you need to entire system to be running?

My project spans both layers and needs to interact with the cross domain messengers. 

> Finally, you could also create your own copy of the docker-compose.yml except without using build contexts as directories, and just using the images pulled from Docker Hub.

Interesting good point.

**Comment by snario** [comment] 2021-04-28 15:52
This may be a duplicate of #570 — cc @gakonst / @TransmissionsDev / @tynes

**Comment by tynes** [comment] 2021-04-28 16:09
> Finally, you could also create your own copy of the docker-compose.yml except without using build contexts as directories, and just using the images pulled from Docker Hub.

The problem with this is that the hardhat image used as part of the monorepo is not published to dockerhub. There is an `ethereumoptimism/hardhat` image that was published as part of the `optimism-integration` repo

**Comment by TransmissionsDev** [comment] 2021-04-28 17:50
> This may be a duplicate of #570 — cc @gakonst / @TransmissionsDev / @tynes

Possibly yeah, I'm still seeing this issue outside of a submodule now.

**Comment by snario** [comment] 2021-04-28 18:56
Okay I'm going to close this for now then unless you find a compelling reason to keep it distinguished from #570

**Closed by snario** 2021-04-28 18:56 UTC
Labels: C-bug
