### ISSUE TITLE
op-node: Handle malformed/incomplete receipt data from L1

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#8245] opened 2023-11-22 20:52 UTC
Bug-reports specify that Besu as L1 RPC returns receipt data with invalid log-index attributes. Since these can be inferred, rather than logging that the data is wrong, we can correct the data (if the receipts-root still matches the consensus data). This data "hydration" is also already happening for the raw receipts of the debug-geth RPC kind. And then, on the mismatch, just make a verbose log of what's wrong about the response exactly, so the L1 client can be fixed.

**Comment by ajsutton** [comment] 2023-11-22 21:01
Do we have a link to the bug reports? I know a while back besu was starting log index from 0 for each transaction rather than each block but I thought that had been fixed.

Fixing the data also sounds like a good idea so long as anything important to us is covered by the checks against the block hash.

**Comment by protolambda** [comment] 2023-11-22 21:13
Regarding Besu log index: see the errors in the screenshot in https://github.com/ethereum-optimism/developers/discussions/59#discussioncomment-7519611

**Comment by ajsutton** [comment] 2023-11-22 21:35
Ah yeah that very much looks like https://github.com/hyperledger/besu/issues/4114 which should be fixed in the latest besu (but may have regressed).

**Comment by protolambda** [comment] 2023-11-22 23:51
@ajsutton that issue is a year old, it must have regressed, or the user wouldn't be able to sync the latest L1 chain with it.

**Comment by ajsutton** [comment] 2023-11-23 00:03
oh good point, I missed the 2022 part of the date. The error message would fit perfectly with that bug though...

**Comment by ajsutton** [comment] 2023-11-23 03:07
Ah that fix was only for `eth_getLogs`. Almost certain the `eth_getReceipt` will have the same bug - just seeing if I can find someone with an existing besu node to confirm.

**Comment by ajsutton** [comment] 2023-11-23 03:23
Confirmed, so I've logged https://github.com/hyperledger/besu/issues/6204

**Comment by protolambda** [comment] 2024-01-05 01:05
Looks like this was fixed in Besu. Can we close this issue? @ajsutton

**Closed as completed** 2024-06-17 22:25 UTC
Labels: A-op-node
