### ISSUE TITLE
Out of gas when calling estimateGas on valid transactions on Optimism Goerli

### ISSUE THREAD

**Issue by matYang** [ethereum-optimism/optimism#4798] opened 2023-01-28 20:36 UTC
**Describe the bug**
when trying to estimate gas required for a transaction by calling contract.estimateGas.func(...), I get error `{"code":-32000,"message":"gas required exceeds allowance (100000)"}`

This is happening to all of our existing code base in staging endpoint that interacts with Optimism Goerli where gas consumption is higher than `100,000`. The same code was working fine before. We did test after Bedrock upgrade.

**To Reproduce**
1. find a contract function that would consume more than `100,000` gas
2. get gasLimit by calling contract.estimateGas.function()
3. error `gas required exceeds allowance (100000)` is thrown

**Expected Behavior**
gasLimit is returned

**System Specs:**
 - OS: local and staging env, both calling Optimism Goerli
 - Endpoint: Infura
 - Package: estimateGas in ethers v5, and estimate in ethers v4, both failing

**Additional Information:**
If I specify a high gas limit in the `estimateGas` call, it works as expected, the proper gas limit is returned. This leads me to suspect the default gas limit calculation logic may be broken, or some default values changed recently, but I cannot find relevant information. For now we are unblocked by setting a high gas limit when calling `estimateGas.

**Comment by smartcontracts** [comment] 2023-01-30 19:25
Hi, what RPC provider are you interacting with? Are you running your own node?

**Comment by matYang** [comment] 2023-02-01 19:03
It is Infura's Optimism Goerli endpoint, https://optimism-goerli.infura.io/v3

**Comment by fainashalts** [comment] 2023-02-02 00:00
Hi there! 👋 I can confirm, am experiencing the same issue with the same endpoint. Was fine before, my code has not changed. This exact error used to be an issue perhaps a year/1.5 years ago but had been resolved afaik.

**Comment by smartcontracts** [comment] 2023-02-06 16:09
@matYang @fainashalts are you able to confirm that you're not experiencing this behavior on other RPC providers or on paid Infura endpoints?

**Comment by fainashalts** [comment] 2023-02-06 18:59
> @matYang @fainashalts are you able to confirm that you're not experiencing this behavior on other RPC providers or on paid Infura endpoints?

I have an account with Infura and have enabled the add-on. I'll try to set up with Alchemy later to see if that helps and will update here if it makes a difference!

**Comment by smartcontracts** [comment] 2023-02-06 21:14
Infura reports that this has been fixed on their end, could someone confirm?

**Comment by GraceFNR** [comment] 2023-02-07 06:29
Halo, it looks like I had a similar problem, I was using the endpoint provided by the academy and the code from the optimism-tutorial(https://github.com/ethereum-optimism/optimism-tutorial/blob/main/cross-dom-bridge-eth/index.js) while doing withdraw.

{"jsonrpc":"2.0","id":69,"error":{"code":-32000,"message":"gas required exceeds allowance (1999)"}}

**Comment by matYang** [comment] 2023-02-08 04:29
I just tested with code before patch, can confirm the problem has been resolved, we'll revert our patch for this issue.

Out of curiosity before we close this, could you share what happened with Infura? I wonder what they did that would lead to this weird behavior

**Comment by smartcontracts** [comment] 2023-02-08 20:35
Infura was setting `--miner.gaslimit=100000` in their nodes to avoid a potential performance issue because the 25mil gas limit + blocks every 2 seconds can create some bottlenecks. Not sure how they worked around that, but they removed that flag.

**Comment by smartcontracts** [comment] 2023-02-08 20:35
Going to close this!

**Closed by smartcontracts** 2023-02-08 20:35 UTC
Labels: C-customer-issue
