### ISSUE TITLE
Transaction that *should revert* does not when specifying a fixed gas limit

### ISSUE THREAD

**Issue by TransmissionsDev** [ethereum-optimism/optimism#740] opened 2021-05-04 00:24 UTC
**Describe the bug**
This transaction does not revert (or at least according to the waffle assertion it does not).

**To Reproduce**
Here's a reproduction branch:
https://github.com/Rari-Capital/nova/tree/gasLimitNoRevertRepro

<img width="398" alt="Screen Shot 2021-05-03 at 5 25 13 PM" src="https://user-images.githubusercontent.com/26209401/116948559-871c7c80-ac34-11eb-896d-3bb6c0b6c923.png">

<img width="437" alt="Screen Shot 2021-05-03 at 5 25 43 PM" src="https://user-images.githubusercontent.com/26209401/116948583-98658900-ac34-11eb-991e-88b177c4c670.png">

**Expected behavior**
The transaction being called should *always* revert.

**Comment by maurelian** [comment] 2021-05-04 00:26
Thanks for providing a repro branch, what do we do with it, `yarn test`?

**Comment by TransmissionsDev** [comment] 2021-05-04 00:27
Yep as long as you've got an instance of l2geth running.

**Comment by TransmissionsDev** [comment] 2021-05-04 00:28
This is kind of an old issue but I just wanted to make sure it was looked into, it might have been fixed by one of these recent commits actually. I would try myself but I cannot build the ops docker images due to #675 😅

**Comment by smartcontracts** [comment] 2021-05-23 23:00
Ok sorry I'm just getting around to this today. I believe that this is actually intended behavior for Geth. To check this, I made a simple test contract:

```solidity
contract Reverter {
    function doRevert() public {
        revert("THIS IS A REVERT");
    }
}
```

And ran the following test against a local (standard Ethereum) geth node:

```js
const hre = require('hardhat')
const { expect } = require('chai')

describe('Reverter', () => {
    it('should revert', async () => {
        const factory = await hre.ethers.getContractFactory('Reverter')
        const contract = await factory.deploy()

        await expect(
            contract.doRevert({
                gasLimit: 5000000
            })
        ).to.be.revertedWith('THIS IS A REVERT')
    })
})
```

Here's the result:

```
  Reverter
    1) should revert


  0 passing (130ms)
  1 failing

  1) Reverter
       should revert:

      AssertionError: Expected transaction to be reverted
      + expected - actual

      -Transaction NOT reverted.
      +Transaction reverted.
```

**Comment by smartcontracts** [comment] 2021-05-23 23:03
The reason the transaction does not appear to revert is because setting a fixed gas limit means Geth will not perform gas estimation and therefore will not catch the revert before executing the transaction. Notably, the following test *does* pass against both normal geth and l2geth:

```
const hre = require('hardhat')
const chai = require('chai')
const chaiAsPromised = require('chai-as-promised')
const expect = chai.expect

chai.use(chaiAsPromised)

describe('Reverter', () => {
    it('should revert', async () => {
        const factory = await hre.ethers.getContractFactory('Reverter')
        const contract = await factory.deploy()

        const result = await contract.doRevert({
            gasLimit: 5000000
        })
        
        await expect(
            result.wait()    
        ).to.be.rejectedWith('transaction failed')
    })
})
```

I hope this explains the issue. I'm going to close this for now. If you believe this is *not* the correct behavior of standard geth, please comment and I will reopen the issue.

**Closed by smartcontracts** 2021-05-23 23:04 UTC
Labels: C-bug, P-unconfirmed

**Comment by TransmissionsDev** [comment] 2021-05-24 00:06
> The reason the transaction does not appear to revert is because setting a fixed gas limit means Geth will not perform gas estimation and therefore will not catch the revert before executing the transaction. Notably, the following test _does_ pass against both normal geth and l2geth:
> 
> ```
> const hre = require('hardhat')
> const chai = require('chai')
> const chaiAsPromised = require('chai-as-promised')
> const expect = chai.expect
> 
> chai.use(chaiAsPromised)
> 
> describe('Reverter', () => {
>     it('should revert', async () => {
>         const factory = await hre.ethers.getContractFactory('Reverter')
>         const contract = await factory.deploy()
> 
>         const result = await contract.doRevert({
>             gasLimit: 5000000
>         })
>         
>         await expect(
>             result.wait()    
>         ).to.be.rejectedWith('transaction failed')
>     })
> })
> ```
> 
> Result:
> 
> ```
>   Reverter
>     ✓ should revert (127ms)
> 
> 
>   1 passing (129ms)
> ```
> 
> I hope this explains the issue. I'm going to close this for now. If you believe this is _not_ the correct behavior of standard geth, please comment and I will reopen the issue.

Ah interesting gotcha. Sounds like something that should be fixed at the waffle level (they're not considering geth behavior).

Thanks for looking into it!
