### ISSUE TITLE
Unable to sync local optimism node

### ISSUE THREAD

**Issue by nate-staked** [ethereum-optimism/optimism#2058] opened 2022-01-24 02:18 UTC
Using this repo: https://github.com/optimisticben/op-replica

But filing the issue in this repo as per request.

My `.env` file:
```
COMPOSE_FILE=replica.yml:replica-shared.yml
ETH_NETWORK=mainnet
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://mainnet.infura.io/v3/<redacted>
DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT=https://mainnet.optimism.io
REPLICA_HEALTHCHECK__ETH_NETWORK_RPC_PROVIDER=https://mainnet.optimism.io
SHARED_ENV_PATH=./kustomize/replica/envs/mainnet
DTL_IMAGE_TAG=0.5.11
L2GETH_IMAGE_TAG=0.5.7
L2GETH_HTTP_PORT=9991
DTL_PORT=7878
```

The containers start off looking healthy:
```
errexit         on
noglob          off
ignoreeof       off
monitor         off
noexec          off
xtrace          off
verbose         off
noclobber       off
allexport       off
notify          off
nounset         off
vi              off
pipefail        off
/geth/geth/chaindata missing, running geth init
Retrieving genesis file https://storage.googleapis.com/optimism/mainnet/genesis-v0.5.0.json
Connecting to storage.googleapis.com (173.194.220.128:443)
saving to '/tmp/tmp.cFofek/genesis.json'
genesis.json           0% |                                | 35768 --:--:-- ETA
genesis.json           0% |                                |  860k  0:14:37 ETA
genesis.json           1% |                                | 6718k  0:02:41 ETA
genesis.json           4% |*                               | 15.2M  0:01:29 ETA
genesis.json           6% |**                              | 24.7M  0:01:07 ETA
genesis.json           9% |***                             | 34.5M  0:00:56 ETA
genesis.json          11% |***                             | 42.1M  0:00:52 ETA
genesis.json          14% |****                            | 50.9M  0:00:48 ETA
genesis.json          16% |*****                           | 59.7M  0:00:44 ETA
genesis.json          19% |******                          | 68.0M  0:00:42 ETA
genesis.json          21% |******                          | 76.5M  0:00:40 ETA
genesis.json          23% |*******                         | 85.8M  0:00:38 ETA
genesis.json          25% |********                        | 91.5M  0:00:37 ETA
genesis.json          27% |********                        | 97.3M  0:00:37 ETA
genesis.json          30% |*********                       |  107M  0:00:34 ETA
genesis.json          30% |*********                       |  110M  0:00:35 ETA
errexit         on
noglob          off
ignoreeof       off
monitor         off
noexec          off
xtrace          off
verbose         off
noclobber       off
allexport       off
notify          off
nounset         off
vi              off
pipefail        off
/geth/geth/chaindata missing, running geth init
Retrieving genesis file https://storage.googleapis.com/optimism/mainnet/genesis-v0.5.0.json
Connecting to storage.googleapis.com (173.194.220.128:443)
saving to '/tmp/tmp.DojMNi/genesis.json'
genesis.json           0% |                                | 27758 --:--:-- ETA
genesis.json           0% |                                |  646k  0:19:01 ETA
genesis.json           1% |                                | 4638k  0:03:55 ETA
genesis.json           2% |                                | 10.7M  0:02:09 ETA
genesis.json           5% |*                               | 20.0M  0:01:24 ETA
genesis.json           7% |**                              | 28.1M  0:01:10 ETA
genesis.json           9% |***                             | 35.3M  0:01:03 ETA
genesis.json          12% |***                             | 43.4M  0:00:57 ETA
genesis.json          13% |****                            | 49.6M  0:00:55 ETA
genesis.json          16% |*****                           | 57.6M  0:00:52 ETA
genesis.json          18% |*****                           | 65.9M  0:00:48 ETA
genesis.json          21% |******                          | 75.4M  0:00:44 ETA
genesis.json          23% |*******                         | 84.6M  0:00:41 ETA
genesis.json          25% |********                        | 89.9M  0:00:41 ETA
genesis.json          27% |********                        | 96.6M  0:00:40 ETA
genesis.json          29% |*********                       |  104M  0:00:38 ETA
genesis.json          31% |**********                      |  112M  0:00:37 ETA
genesis.json          33% |**********                      |  120M  0:00:35 ETA
genesis.json          35% |***********                     |  125M  0:00:35 ETA
genesis.json          37% |***********                     |  133M  0:00:33 ETA
genesis.json          39% |************                    |  140M  0:00:32 ETA
genesis.json          40% |*************                   |  145M  0:00:32 ETA
genesis.json          43% |*************                   |  154M  0:00:30 ETA
genesis.json          45% |**************                  |  161M  0:00:28 ETA
genesis.json          47% |***************                 |  171M  0:00:27 ETA
genesis.json          50% |****************                |  180M  0:00:25 ETA
genesis.json          52% |****************                |  188M  0:00:24 ETA
genesis.json          55% |*****************               |  197M  0:00:22 ETA
genesis.json          57% |******************              |  206M  0:00:21 ETA
genesis.json          59% |*******************             |  213M  0:00:20 ETA
genesis.json          61% |*******************             |  220M  0:00:19 ETA
genesis.json          64% |********************            |  228M  0:00:17 ETA
genesis.json          66% |*********************           |  236M  0:00:16 ETA
genesis.json          67% |*********************           |  241M  0:00:16 ETA
genesis.json          70% |**********************          |  251M  0:00:14 ETA
genesis.json          72% |***********************         |  259M  0:00:13 ETA
genesis.json          74% |***********************         |  267M  0:00:12 ETA
genesis.json          76% |************************        |  274M  0:00:11 ETA
genesis.json          79% |*************************       |  284M  0:00:09 ETA
genesis.json          82% |**************************      |  294M  0:00:08 ETA
genesis.json          85% |***************************     |  304M  0:00:07 ETA
genesis.json          87% |***************************     |  312M  0:00:06 ETA
genesis.json          90% |****************************    |  321M  0:00:04 ETA
genesis.json          92% |*****************************   |  330M  0:00:03 ETA
genesis.json          95% |******************************  |  339M  0:00:02 ETA
genesis.json          97% |******************************* |  347M  0:00:01 ETA
genesis.json          99% |******************************* |  355M  0:00:00 ETA
genesis.json         100% |********************************|  357M  0:00:00 ETA
'/tmp/tmp.DojMNi/genesis.json' saved
checksums match
GENESIS_SHA256SUM: 361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a == L2GETH_GENESIS_URL_SHA256SUM: 361ff81fff4cc71e5f0bf43b0b982f5cfd08d068f730b9a61516fe1fa8fd914a
INFO [01-23|22:28:26.637] Maximum peer count                       ETH=50 LES=0 total=50
INFO [01-23|22:28:26.643] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [01-23|22:28:26.650] Allocated cache and file handles         database=/geth/geth/chaindata cache=16.00MiB handles=16
INFO [01-23|22:28:26.665] Writing custom genesis block 
WARN [01-23|23:41:20.720] Database compacting, degraded performance database=/geth/geth/chaindata
Killed
errexit         on
noglob          off
ignoreeof       off
monitor         off
noexec          off
xtrace          off
verbose         off
noclobber       off
allexport       off
notify          off
nounset         off
vi              off
pipefail        off
/geth/geth/chaindata existing, skipping geth init
/geth/keystore missing, running account import
INFO [01-23|23:56:30.132] Maximum peer count                       ETH=50 LES=0 total=50
INFO [01-23|23:56:30.133] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Address: {00000398232e2064f896018496b4b44b3d62751f}
l2geth setup complete
errexit         on
noglob          off
ignoreeof       off
monitor         off
noexec          off
xtrace          off
verbose         off
noclobber       off
allexport       off
notify          off
nounset         off
vi              off
pipefail        off
INFO [01-23|23:56:32.846] Maximum peer count                       ETH=50 LES=0 total=50
INFO [01-23|23:56:32.847] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [01-23|23:56:32.850] Starting peer-to-peer node               instance=Geth/v1.9.10-stable/linux-amd64/go1.15.15
INFO [01-23|23:56:32.851] Allocated trie memory caches             clean=512.00MiB dirty=0.00B
INFO [01-23|23:56:32.852] Allocated cache and file handles         database=/geth/geth/chaindata cache=512.00MiB handles=524288
INFO [01-23|23:56:33.230] Opened ancient database                  database=/geth/geth/chaindata/ancient
INFO [01-23|23:56:33.235] Writing default main-net genesis block 
INFO [01-23|23:56:35.365] Persisted trie from memory database      nodes=24762 size=2.91MiB time=241.7823ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-82.00B
INFO [01-23|23:56:35.366] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: 9069000, Muir Glacier: 9200000, Engine: ethash}"
INFO [01-23|23:56:35.366] Disk storage enabled for ethash caches   dir=/geth/geth/ethash count=3
INFO [01-23|23:56:35.366] Disk storage enabled for ethash DAGs     dir=/root/.ethash     count=2
INFO [01-23|23:56:35.372] Initialising Ethereum protocol           versions="[64 63]" network=10 dbversion=<nil>
WARN [01-23|23:56:35.372] Upgrade blockchain database version      from=<nil> to=7
INFO [01-23|23:56:35.373] Loaded most recent local header          number=0 hash=bfef5d…2fe952 td=17179869184 age=52y9mo3w
INFO [01-23|23:56:35.373] Loaded most recent local full block      number=0 hash=bfef5d…2fe952 td=17179869184 age=52y9mo3w
INFO [01-23|23:56:35.373] Loaded most recent local fast block      number=0 hash=bfef5d…2fe952 td=17179869184 age=52y9mo3w
INFO [01-23|23:56:35.378] Regenerated local transaction journal    transactions=0 accounts=0
INFO [01-23|23:56:35.378] Running in verifier mode                 sync-backend=l2
INFO [01-23|23:56:35.379] Configured rollup client                 url=http://data-transport-layer:7878 chain-id=1 ctc-deploy-height=13596466
INFO [01-23|23:56:39.335] Connected to upstream service 
INFO [01-23|23:56:39.480] Initializing initial OVM Context         ctc-deploy-height=13596466
INFO [01-23|23:56:41.103] Initialized Latest L1 Info               blocknumber=13596466 timestamp=1636654670
INFO [01-23|23:56:41.103] Initial Rollup State                     state=0x2bc751133055934c02bb16744700cb37be2061b8b824b9fc9bdd9444dd589dc4 index=<nil> queue-index=<nil> verified-index=<nil>
INFO [01-23|23:56:41.113] Allocated fast sync bloom                size=512.00MiB
INFO [01-23|23:56:41.128] Backend Config                           max-calldata-size=40000 gas-limit=15000000 is-verifier=true using-ovm=true
INFO [01-23|23:56:41.147] IPC endpoint opened                      url=/geth/geth.ipc
INFO [01-23|23:56:41.149] HTTP endpoint opened                     url=http://0.0.0.0:8545              cors=* vhosts=*
INFO [01-23|23:56:41.151] WebSocket endpoint opened                url=ws://[::]:8546
INFO [01-23|23:56:41.178] New local node record                    seq=1 id=c5c7649a7a2a54a8 ip=127.0.0.1 udp=0 tcp=30303
INFO [01-23|23:56:41.178] Started P2P networking                   self="enode://24eed531e183167a11b544c9a5e6737333c242b4ae298d567c950d08acd940d9d6d9496c8cada4669c68049928b6043677aef89417857ffd364be2f38bbf02af@127.0.0.1:30303?discport=0"
INFO [01-23|23:56:42.890] Unlocked account                         address=0x00000398232E2064F896018496b4b44b3D62751F
INFO [01-23|23:56:42.891] Transaction pool price threshold updated price=0
INFO [01-23|23:56:42.891] Updated mining threads                   threads=0
INFO [01-23|23:56:42.891] Transaction pool price threshold updated price=0
INFO [01-23|23:56:42.891] Initializing Sync Service 
INFO [01-23|23:56:42.892] Set L2 Gas Price                         gasprice=0
INFO [01-23|23:56:42.892] Set L1 Gas Price                         gasprice=0
INFO [01-23|23:56:42.892] Set batch overhead                       overhead=0
INFO [01-23|23:56:42.892] Set scalar                               scalar=0
INFO [01-23|23:56:42.892] Starting Verifier Loop                   poll-interval=1s timestamp-refresh-threshold=5m0s
INFO [01-23|23:56:42.903] Syncing transaction range                start=0 end=183000 backend=l2
ERROR[01-23|23:56:42.926] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:42.926] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:42.926] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-23|23:56:43.897] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-23|23:56:43.903] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:43.903] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:43.903] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-23|23:56:44.900] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-23|23:56:44.911] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:44.911] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:44.912] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-23|23:56:45.897] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-23|23:56:45.905] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:45.905] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:45.905] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-23|23:56:46.897] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-23|23:56:46.907] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:46.907] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-23|23:56:46.907] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-23|23:56:47.768] Syncing transaction range                start=1 end=183000 backend=l2
```

The errors just loop after a while:
```
ERROR[01-24|02:11:50.523] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:50.524] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:51.566] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:51.575] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:51.575] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:51.611] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:52.526] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:52.548] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:52.548] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:52.548] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:54.030] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:54.034] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:54.034] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:54.034] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:54.712] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:54.999] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:54.999] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:54.999] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:55.784] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:55.822] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:55.822] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:55.824] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:56.646] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:56.950] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:56.950] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:56.951] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:57.515] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:57.523] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:57.523] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:57.523] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:58.514] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:58.517] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:58.517] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:58.517] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:11:59.514] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:11:59.518] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:59.519] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:11:59.520] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:12:00.524] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:12:00.528] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:12:00.528] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:12:00.528] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:12:01.515] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:12:01.520] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:12:01.520] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:12:01.520] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
INFO [01-24|02:12:02.526] Syncing transaction range                start=1 end=183000 backend=l2
ERROR[01-24|02:12:02.536] Problem committing transaction           msg="Cannot commit transaction in miner"
ERROR[01-24|02:12:02.536] Got error waiting for transaction to be added to chain msg="Cannot commit transaction in miner"
ERROR[01-24|02:12:02.536] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: Cannot commit transaction in miner"
```

**Comment by qbzzt** [comment] 2022-02-08 03:08
I encountered a similar issue with the latest `master` branch. However, when I reverted to the 0.5.8 tag (`@eth-optimism/l2geth@0.5.8`), it worked. So there must have been a bug that was introduced between Jan 25th and today. The 0.5.7 issue may or may not be the same.

Here are the details:

I created a non-docker replica and it mostly works. The problem is that when l2geth gets to transaction 2093461 (https://optimistic.etherscan.io/tx/2093461) it complains there is insufficient balance for the transfer.

ERROR[02-06|20:02:20.094] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
INFO [02-06|20:02:21.091] Syncing transaction range                start=2093461 end=3274980 backend=l2
ERROR[02-06|20:02:21.093] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[02-06|20:02:21.093] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[02-06|20:02:21.093] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
INFO [02-06|20:02:22.091] Syncing transaction range                start=2093461 end=3274980 backend=l2
ERROR[02-06|20:02:22.092] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[02-06|20:02:22.093] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[02-06|20:02:22.093] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"

I don't think it relates to being permitted to download from the endpoint, because the DTL has the entire chain:
ori@replica-nodocker-10:~/gethData/geth$ curl -s http://localhost:7878/eth/syncing?backend=l2 ; echo
{"syncing":false,"currentTransactionIndex":3275011}
ori@replica-nodocker-10:~/gethData/geth$

There doesn't seem to be any problem with that transaction, beyond the fact that it failed ("confirmed": false)
ori@replica-nodocker-10:~/optimism/l2geth$ curl http://localhost:7878/transaction/index/2093461?backend=l2
{"transaction":{"index":2093461,"value":"0x5e259c0e8c4000","batchIndex":null,"blockNumber":13964696,"timestamp":1641644143,"queueOrigin":"sequencer","confirmed":false,"gasLimit":"0","target":"0x0000000000000000000000000000000000000000","origin":null,"data":"0xf8af01830f424083030605943af0441ce31974c9ea6553fdba60c9cd3dfd933d875e259c0e8c4000b84467f68fac0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000037a02817a3c9dc42a0bf1f7874dfd6a598206ebcc233f563e57219b326ff85979ecfa055d0a149d23fa188a8cdbda3315c950349d0ec5a15acfc35e52be1417dc296c1","decoded":{"sig":{"v":0,"r":"0x2817a3c9dc42a0bf1f7874dfd6a598206ebcc233f563e57219b326ff85979ecf","s":"0x55d0a149d23fa188a8cdbda3315c950349d0ec5a15acfc35e52be1417dc296c1"},"value":"0x5e259c0e8c4000","gasLimit":"198149","gasPrice":"1000000","nonce":"1","target":"0x3af0441ce31974c9ea6553fdba60c9cd3dfd933d","data":"0x67f68fac00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000"},"queueIndex":null},"batch":null}

And I know there is sufficient disk space:
ori@replica-nodocker-10:~/optimism/l2geth$ df .
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda1      206228464 59755752 137969660  31% /

I restarted geth, here is what the logs shows:
INFO [02-06|20:20:39.783] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-06|20:20:39.784] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-06|20:20:39.784] Starting peer-to-peer node               instance=Geth/v1.9.10-stable/linux-amd64/go1.17.6
INFO [02-06|20:20:39.784] Allocated trie memory caches             clean=512.00MiB dirty=0.00B
INFO [02-06|20:20:39.784] Allocated cache and file handles         database=/home/ori/gethData/geth/chaindata cache=512.00MiB handles=524288
INFO [02-06|20:20:39.976] Opened ancient database                  database=/home/ori/gethData/geth/chaindata/ancient
INFO [02-06|20:20:39.977] Initialised chain configuration          config="{ChainID: 10 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Berlin: <nil>, Engine: clique}"
INFO [02-06|20:20:39.979] Initialising Ethereum protocol           versions="[64 63]" network=10 dbversion=7
INFO [02-06|20:20:39.993] Loaded most recent local header          number=2093461 hash=66bc2f…b156d9 td=4186923 age=4w1d8h
INFO [02-06|20:20:39.993] Loaded most recent local full block      number=2093461 hash=66bc2f…b156d9 td=4186923 age=4w1d8h
INFO [02-06|20:20:39.993] Loaded most recent local fast block      number=2093461 hash=66bc2f…b156d9 td=4186923 age=4w1d8h
INFO [02-06|20:20:40.037] Loaded local transaction journal         transactions=0 dropped=0
INFO [02-06|20:20:40.037] Regenerated local transaction journal    transactions=0 accounts=0
INFO [02-06|20:20:40.037] Running in verifier mode                 sync-backend=l2
INFO [02-06|20:20:40.037] Configured rollup client                 url=http://localhost:7878 chain-id=10 ctc-deploy-height=13596466
INFO [02-06|20:20:40.555] Connected to upstream service 
INFO [02-06|20:20:40.557] Found latest index                       index=2093460
INFO [02-06|20:20:40.557] Found latest queue index                 queue-index=39074
INFO [02-06|20:20:40.558] Found incorrect staring queue index, fixing old=0xc0000e1150 new=0xc002e6eea8
INFO [02-06|20:20:40.558] Initialized Latest L1 Info               blocknumber=13964696 timestamp=1641644143
INFO [02-06|20:20:40.559] Initial Rollup State                     state=0x43caf7818324748d004b1a2d1635f3a2a4b38acdf0f0e6ff2cf4986f3bc1f77e index=2093460 queue-index=39074 verified-index=<nil>
WARN [02-06|20:20:40.559] Switch sync mode from fast sync to full sync 
INFO [02-06|20:20:40.563] Backend Config                           max-calldata-size=40000 gas-limit=15000000 is-verifier=true using-ovm=true
INFO [02-06|20:20:40.581] New local node record                    seq=4 id=f923914ba9d45987 ip=127.0.0.1 udp=0 tcp=30303
INFO [02-06|20:20:40.581] Started P2P networking                   self="enode://62670fca60b6dc76d37f9fbec82073e249038854318e5ca7b63ee6a3335dbc4b2e08790a0dce9fe3cc9599321e9eac14f08f21c9c37fe7379a448e62871e44d5@127.0.0.1:30303?discport=0"
INFO [02-06|20:20:40.582] IPC endpoint opened                      url=/home/ori/gethData/geth.ipc
INFO [02-06|20:20:40.582] HTTP endpoint opened                     url=http://0.0.0.0:8545         cors=* vhosts=*
INFO [02-06|20:20:40.583] WebSocket endpoint opened                url=ws://[::]:8546
INFO [02-06|20:20:41.391] Unlocked account                         address=0x00000398232E2064F896018496b4b44b3D62751F
INFO [02-06|20:20:41.391] Transaction pool price threshold updated price=0
INFO [02-06|20:20:41.391] Transaction pool price threshold updated price=0
INFO [02-06|20:20:41.391] Initializing Sync Service 
INFO [02-06|20:20:41.413] Set L2 Gas Price                         gasprice=1000000
INFO [02-06|20:20:41.413] Set L1 Gas Price                         gasprice=69429574812
INFO [02-06|20:20:41.415] Set batch overhead                       overhead=2100
INFO [02-06|20:20:41.416] Set scalar                               scalar=1.24
INFO [02-06|20:20:41.417] Starting Verifier Loop                   poll-interval=1s timestamp-refresh-threshold=5m0s
INFO [02-06|20:20:41.418] Syncing transaction range                start=2093461 end=3275191 backend=l2
ERROR[02-06|20:20:41.438] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[02-06|20:20:41.438] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[02-06|20:20:41.439] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
INFO [02-06|20:20:42.419] Syncing transaction range                start=2093461 end=3275191 backend=l2
ERROR[02-06|20:20:42.420] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[02-06|20:20:42.420] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[02-06|20:20:42.420] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
INFO [02-06|20:20:43.418] Syncing transaction range                start=2093461 end=3275191 backend=l2
ERROR[02-06|20:20:43.420] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[02-06|20:20:43.420] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[02-06|20:20:43.420] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
INFO [02-06|20:20:44.419] Syncing transaction range                start=2093461 end=3275191 backend=l2
ERROR[02-06|20:20:44.421] Problem committing transaction           msg="insufficient balance for transfer"
ERROR[02-06|20:20:44.421] Got error waiting for transaction to be added to chain msg="insufficient balance for transfer"
ERROR[02-06|20:20:44.421] Could not verify                         error="Verifier cannot sync transactions with BackendL2: Verifier cannot sync transactions with backend l2: Cannot sync transactions with backend l2: Cannot apply transaction: insufficient balance for transfer"
My latest theory is that the 0.5.8 release (the docker image used by default for a replica) is good, but the 0.5.11 release (the one I got when I cloned the mono-repository) can't accept that particular transaction. I'm now running a dockerless 0.5.8 and I'll see if it'll synchronize. If so:

I'll have the directions for Huobi.
We'll know a bit about the problem.


What could be causing this? There shouldn't be a problem with syncing the fact that a failed transaction failed. I can't make progress with Huobi, or with the directions for a dockerless replica in general, without a solution to this.

PS
--
I tried the same thing with 32 GB of RAM, and it failed on the same transaction.

PPS
---
Turning off the verifier:
export ROLLUP_VERIFIER_ENABLE=false
doesn't help either.

**Comment by qbzzt** [comment] 2022-02-08 13:34
The error the Huobi encountered, BTW, is 

```
INFO [02-08|10:14:36.689] New block                                index=530   l1-timestamp=1636673543 l1-blocknumber=13597848 tx-hash=0xd63fadc1ff2ccf3cf876727fe1fab4aa1baa7f29a5540fb54dc3658cb2d17bf1 queue-orign=sequencer gas=116237  fees=1.16237e-07  elapsed=1.512ms 
ERROR[02-08|10:14:36.691] Blocknumber monotonicity violation       hash=0x7bf9e5fa0c269d9a911ee7f72965378aecedcac6d0bb08bb7815a675c10c36b6
```

**Comment by smartcontracts** [comment] 2022-03-24 13:52
@nate-staked are you still experiencing this with the latest versions of everything?

**Comment by smartcontracts** [comment] 2022-03-25 21:47
I'm going to close this since the issue is quite old now (2 months) and there hasn't been any additional information. If you are still experiencing this issue, please let me know and I will be happy to re-open. Thank you! :pray:

**Closed by smartcontracts** 2022-03-25 21:47 UTC
Labels: C-bug, P-unconfirmed, M-l2geth, N-mainnet
