### ISSUE TITLE
Fund L2 geth accounts with ETH for local network

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#657] opened 2021-04-27 21:28 UTC
**Is your feature request related to a problem? Please describe.**
Right now, `getGasPrice` on L2 geth returns 1gwei. However, no accounts in L2 are currently funded with ETH, so they can't pay their fees on L2. This means that no transactions will go through on L2 unless `gasPrice` is hardcoded to 0. We need to fund a set of L2 accounts with ETH from L1.

**Describe the solution you'd like**
On startup, we can just `getAccounts` from the L1 chain to get all of the accounts with 1000 ETH on L1 and deposit 100 of that ETH to L2 geth from each of those accounts.

**Additional context**
If we want to solve this issue in the short term, we can have `gasPrice` in L2 be set to 0 gwei.

**Comment by snario** [comment] 2021-04-27 21:40
We could do:
- A genesis file (i.e., pass to `geth`)
- Send initialization transactions

**Comment by gakonst** [comment] 2021-04-28 08:59
I prefer the genesis file approach.

**Comment by platocrat** [comment] 2021-05-03 16:16
@snario @gakonst any updates on an implementation for a solution?

**Comment by gakonst** [comment] 2021-05-04 09:29
Nobody has been working on this. I can take a stab.

**Comment by tynes** [comment] 2021-05-10 22:11
I'd like for the initial state dump to have the same schema as the genesis file. It would really simplify things. The problem is that the state dump format has the ABIs and we depend on them while the genesis file format doesn't include ABIs. Perhaps we could extend the genesis file format to include the ABIs which would get parsed by opti-geth but otherwise ignored by normal geth. This would enable us to reduce the diff by getting rid of the opti-geth specific state application logic for the initial state

> Currently we use the dev mode genesis file and that feels overloaded.

I agree that this is overloaded, we do have plans to move away from using the clique `consensus.Engine`

**Comment by smartcontracts** [comment] 2021-06-17 22:17
Sort of covered in regenesis 0.4.0 so I'm going to close this. We always automatically fund the default hardhat list of accounts.

**Closed by smartcontracts** 2021-06-17 22:17 UTC
Labels: A-integration-tests, C-enhancement, C-meta
