### ISSUE TITLE
'truffle test' fails with TIMEOUT without --compile-none flag

### ISSUE THREAD

**Issue by sean-lawless** [ethereum-optimism/optimism#1848] opened 2021-12-02 23:02 UTC
**Describe the bug**
With Optimistic Etherem development node (Windows 10), 'truffle test' fails after compiling many contracts with TIMEOUT.

**To Reproduce**

Execute "truffle test" and it fails with TIMEOUT
Execute "truffle test --compile-none" success

**Expected behavior**
The command to compile, deploy and run the tests.

**Screenshots**

Output dump at the end.

**System Specs:**
 - OS: Windows 10 DockerDesktop
 - Package Version (or commit hash): Node 12.

**Additional context**
 Problem (timeout) does NOT occur with Metacoin example. Related to how many smart contracts are being compiled?

Logs:

C:\Source\ImmutableEcosystem>truffle test --compile-none --network optimistic
Using network 'optimistic'.

Compiling your contracts...
===========================
> Compilation skipped because --compile-none option was passed.

  Deployed string common  0x44863F234b137A395e5c98359d16057A9A1fAc55
  Deployed entity  0x1c39BA375faB6a9f6E0c01B9F49d488e101C2011
  Deployed product  0xc0c5618f0F3Fa66b496F2940f373DC366d765BAe
  Deployed creator token  0x6212cb549De37c25071cF506aB7E115D140D9e42
  Deployed activate token  0xf4AE7E15B1012edceD8103510eeB560a9343AFd3
  Deployed product activate 0x0bF7dE8d71820840063D4B8653Fd3F0618986faF
Deployed custom token  0x5E5713a0d915701F464DEbb66015adD62B2e6AE9

  Contract: ImmutableEcosystem
    √ Check if upgradeable contracts work (6452ms)
    √ Restrict the activate token (required) (295ms)
    √ Change ImmutableEcosystem owner (1898ms)
    √ Find or create new entity (409ms)
    √ Update an organization status (775ms)
    √ Find or create a new product  (854ms)
    √ Create a duplicate product  (1222ms)
...
    √ Purchased third party custom token activation license (17533ms)
    √ Move a resold custom token activation license (15041ms)
    √ Read all the entities (646ms)
    √ Read all the products for the first entity (1770ms)
    √ Read all the releases for the first entity, first product (2202ms)
    √ Read all (15) activations for the fourth entity (enduser/enduser2) (550ms)
    √ Offer product activation license for resale (14261ms)
    √ Read all for sale activations from the ecosystem (724ms)

  76 passing (19m)
  
C:\Source\ImmutableEcosystem>truffle test --network optimistic
Using network 'optimistic'.

Compiling your contracts...
===========================
> Compiling @openzeppelin\contracts-upgradeable\access\OwnableUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\proxy\utils\Initializable.sol
> Compiling @openzeppelin\contracts-upgradeable\security\PullPaymentUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC20\ERC20Upgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC20\IERC20Upgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC20\extensions\IERC20MetadataUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\ERC721Upgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\IERC721ReceiverUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\IERC721Upgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\extensions\ERC721BurnableUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\extensions\ERC721EnumerableUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\extensions\ERC721URIStorageUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\extensions\IERC721EnumerableUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\token\ERC721\extensions\IERC721MetadataUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\utils\AddressUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\utils\ContextUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\utils\StringsUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\utils\escrow\EscrowUpgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\utils\introspection\ERC165Upgradeable.sol
> Compiling @openzeppelin\contracts-upgradeable\utils\introspection\IERC165Upgradeable.sol
> Compiling .\contracts\ActivateToken.sol
> Compiling .\contracts\CreatorToken.sol
> Compiling .\contracts\CustomToken.sol
> Compiling .\contracts\ImmutableEntity.sol
> Compiling .\contracts\ImmutableProduct.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\ProductActivate.sol
> Compiling .\contracts\StringCommon.sol
> Artifacts written to C:\Users\slawl\AppData\Local\Temp\test--3192-RO4oTENzSUf3
> Compiled successfully using:
   - solc: 0.8.9+commit.e5eed63a.Emscripten.clang

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  code: -32603,
  message: 'ESOCKETTIMEDOUT',
  data: { originalError: { code: 'ESOCKETTIMEDOUT', connect: false } },
  stack: 'Error: ESOCKETTIMEDOUT\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\slawl\\Source\\ImmutableEcosystem\\node_modules\\request\\request.js:816:19)\n' +
    '    at Object.onceWrapper (events.js:481:28)\n' +
    '    at ClientRequest.emit (events.js:375:28)\n' +
    '    at Socket.emitRequestTimeout (_http_client.js:790:9)\n' +
    '    at Object.onceWrapper (events.js:481:28)\n' +
    '    at Socket.emit (events.js:387:35)\n' +
    '    at Socket._onTimeout (net.js:484:8)\n' +
    '    at listOnTimeout (internal/timers.js:557:17)\n' +
    '    at processTimers (internal/timers.js:500:7)'
})
    at Web3ProviderEngine.emit (events.js:364:17)
    at C:\Users\slawl\Source\ImmutableEcosystem\node_modules\@trufflesuite\web3-provider-engine\index.js:57:14
    at afterRequest (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\@trufflesuite\web3-provider-engine\index.js:151:21)
    at C:\Users\slawl\Source\ImmutableEcosystem\node_modules\@trufflesuite\web3-provider-engine\index.js:176:21
    at C:\Users\slawl\Source\ImmutableEcosystem\node_modules\@trufflesuite\web3-provider-engine\index.js:238:9
    at C:\Users\slawl\Source\ImmutableEcosystem\node_modules\async\internal\once.js:12:16
    at replenish (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\async\internal\eachOfLimit.js:61:25)
    at C:\Users\slawl\Source\ImmutableEcosystem\node_modules\async\internal\eachOfLimit.js:71:9
    at eachLimit (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\async\eachLimit.js:43:36)
    at C:\Users\slawl\Source\ImmutableEcosystem\node_modules\async\internal\doLimit.js:9:16
    at end (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\@trufflesuite\web3-provider-engine\index.js:217:5)
    at Request._callback (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\@trufflesuite\web3-provider-engine\subproviders\rpc.js:36:21)
    at self.callback (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\request\request.js:185:22)
    at Request.emit (events.js:375:28)
    at ClientRequest.<anonymous> (C:\Users\slawl\Source\ImmutableEcosystem\node_modules\request\request.js:819:16)
    at Object.onceWrapper (events.js:481:28)
    at ClientRequest.emit (events.js:375:28)
    at Socket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:481:28)
    at Socket.emit (events.js:387:35)
    at Socket._onTimeout (net.js:484:8)
    at listOnTimeout (internal/timers.js:557:17)
UnhandledRejections detected
Promise {
  <rejected> {
    code: -32603,
    message: 'ESOCKETTIMEDOUT',
    data: { originalError: [Object] },
    stack: 'Error: ESOCKETTIMEDOUT\n' +
      '    at ClientRequest.<anonymous> (C:\\Users\\slawl\\Source\\ImmutableEcosystem\\node_modules\\request\\request.js:816:19)\n' +
      '    at Object.onceWrapper (events.js:481:28)\n' +
      '    at ClientRequest.emit (events.js:375:28)\n' +
      '    at Socket.emitRequestTimeout (_http_client.js:790:9)\n' +
      '    at Object.onceWrapper (events.js:481:28)\n' +
      '    at Socket.emit (events.js:387:35)\n' +
      '    at Socket._onTimeout (net.js:484:8)\n' +
      '    at listOnTimeout (internal/timers.js:557:17)\n' +
      '    at processTimers (internal/timers.js:500:7)'
  }
} {
  code: -32603,
  message: 'ESOCKETTIMEDOUT',
  data: { originalError: { code: 'ESOCKETTIMEDOUT', connect: false } },
  stack: 'Error: ESOCKETTIMEDOUT\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\slawl\\Source\\ImmutableEcosystem\\node_modules\\request\\request.js:816:19)\n' +
    '    at Object.onceWrapper (events.js:481:28)\n' +
    '    at ClientRequest.emit (events.js:375:28)\n' +
    '    at Socket.emitRequestTimeout (_http_client.js:790:9)\n' +
    '    at Object.onceWrapper (events.js:481:28)\n' +
    '    at Socket.emit (events.js:387:35)\n' +
    '    at Socket._onTimeout (net.js:484:8)\n' +
    '    at listOnTimeout (internal/timers.js:557:17)\n' +
    '    at processTimers (internal/timers.js:500:7)'
}

**Comment by smartcontracts** [comment] 2021-12-03 16:43
Do you have a link to the repository where I can reproduce this?

**Comment by sean-lawless** [comment] 2021-12-03 17:54
Not committed yet, will have repo/branch ready by Monday and will update this issue with link. TIMEOUT also occurs with 'truffle deploy' (or even 'truffle deploy --compile-none') but works find with 'truffle migrate --compile-none --network optimistic'. Truffle version 5.4.21.

**Comment by smartcontracts** [comment] 2021-12-03 21:56
Perfect, will look into this as soon as you have a branch ready.

**Comment by sean-lawless** [comment] 2021-12-07 21:39
Ok, latest code is now committed to Main branch of this repo:
https://github.com/ImmutableSoft/ImmutableEcosystem

**Comment by smartcontracts** [comment] 2021-12-10 18:33
Will be taking a look at this today.

**Comment by sean-lawless** [comment] 2021-12-14 15:33
Any luck reproducing?

**Comment by smartcontracts** [comment] 2021-12-14 18:55
@sean-lawless just to confirm, are you running these tests against a local Optimistic Ethereum node? (I assume using the `ops` tool).

**Comment by smartcontracts** [comment] 2021-12-14 19:09
I was not able to reproduce this locally. I ran the tests against a local hardhat node (`truffle test`) and against the local OE setup (`truffle test --network optimistic`) and was able to successfully run the entire test suite both times.

**Comment by sean-lawless** [comment] 2021-12-23 00:00
> I was not able to reproduce this locally.

Similar problem migrating this project to Optimistic Kovan (3 endpoints tested, infura, optimism.io and alchemy). Requires --compile-none or a TIMEOUT after displaying compilation output. Using either 'truffle migrate' or 'truffle deploy'. Windows 10, Node 14.17.1, NPM 6.14.14, Truffle 5.4.21 and HDWalletProvider 1.7.0. Successfully migrated contracts to Optimistic Kovan network using this flag, but it took two tries. First attempt failed like this (https://github.com/trufflesuite/truffle/issues/3468) which led me to this issue (https://github.com/trufflesuite/truffle/issues/3356#issuecomment-826310780) and others using --compile-none flag. Looks like a Truffle issue unrelated to optimism?

**Comment by smartcontracts** [comment] 2021-12-23 15:31
Hmmm... weird. Let's keep an eye on it. If truffle confirms that this is on their end then let's close this issue out.

**Comment by gorojou** [comment] 2022-01-08 21:19
I have the same error with truffle migrate

this is my truffle.config
    ethTestnet: {
      provider: () => new HDWalletProvider(
        mnemonic, 
        'https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161'
      ),
      network_id: 4, //rinkeby
      gas: 5000000,
      gasPrice: 40000000000,
     // confirmations: 1,
     // timeoutBlocks: 400,
      skipDryRun: false,
      websocket: true,
      timeoutBlocks: 90000,
      networkCheckTimeout: 9000000
    },

**Closed** 2022-02-09 15:40 UTC
Labels: C-bug, P-unconfirmed
