### ISSUE TITLE
ETH deposits all return status 0 (Revert)

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#497] opened 2021-04-19 20:25 UTC
Despite succeeding (ETH actually deposits and the correct events are emitted), ETH deposits show status: 0 when they are processed on L2.

**Steps to reproduce the behavior:**
1. Run native eth integration tests
2. Check getTransactionReceipt on the L2 tx hash of a completed ETH deposit.

**Comment by K-Ho** [comment] 2021-04-19 20:29
This is blocking going live with fees. cc @ben-chain  I remember you mentioned knowing the cause of this?

**Comment by ben-chain** [comment] 2021-04-19 20:41
I am pretty sure that this behavior is because we treat calls to predeploys as "pre-execution" WRT the action the user wants to take.  This is because we want e.g. the L2xDM's return status to be ignore and instead return the result of its subcall in `relayMessage`.  However, [this](https://github.com/ethereum-optimism/optimism/blob/35b99b07cf9f3e02496783c565b3f82f7fb55fef/l2geth/core/vm/evm.go#L269) line in geth means that we do not correctly identify the `OVM_ETH` contract as the "intended target" of the finalizeDeposit transaction.

I believe that a quick fix would be modifying this condition so that it correctly sees the `OVM_ETH.finalizeDeposit` call as being the "intended target subcall" whose status should be returned.  However, correctly identifying this is a little hacky.  A more robust solution is to have the execution manager always return data, so that the common pattern is predeploys return the status of their target message, whatever that might be, as discussed here: https://github.com/ethereum-optimism/optimism/issues/474

**Comment by snario** [comment] 2021-04-20 00:58
I've reproduced this here: https://github.com/ethereum-optimism/optimism/pull/502

**Comment by ben-chain** [comment] 2021-04-21 18:07
I thought through this a little bit more, and unfortunately the hotfix I laid out above seems insufficient/difficult to pull off.  The reason is because the fee payment logic within `OVM_ECDSAContractAccount` always produces a call frame into the `OVM_ETH` contract, and it will be hard to differentiate between this frame and the "real" call to OVM_ETH.  We could still solve the problem with deposits, but it could end up manifesting elsewhere.  Therefore, I think the "EM returndata" approach is the right one here.

**Comment by tynes** [comment] 2021-04-28 20:22
Is this fixed by https://github.com/ethereum-optimism/optimism/pull/643 ?

**Comment by K-Ho** [comment] 2021-05-17 18:37
Bump on this, causing confusion with using the gateway - cc @gigamesh

**Closed** 2021-05-26 00:28 UTC
Labels: A-geth, C-bug
