### ISSUE TITLE
Remove onlyRelayer from L1 Messenger

### ISSUE THREAD

**Issue by K-Ho** [ethereum-optimism/optimism#805] opened 2021-05-07 17:34 UTC
**Is your feature request related to a problem? Please describe.**
To enable (and test) self-withdrawals, we'll need the ability for anyone to relay a withdrawal, this means removing the `onlyRelayer` modifier on `relayMessage`

**Describe the solution you'd like**
Just delete the modifier `onlyRelayer` https://github.com/ethereum-optimism/optimism/blob/536e02b54b34608045f9d476d3956062671f687b/packages/contracts/contracts/optimistic-ethereum/OVM/bridge/messaging/OVM_L1CrossDomainMessenger.sol#L81-L90
and remove instances of setting the `OVM_L2MessageRelayer` in the AddressManager

**Comment by snario** [comment] 2021-05-07 20:52
This is a duplicate of #623

**Closed by snario** 2021-05-07 20:52 UTC
