### ISSUE TITLE
Docker services sometimes can't retrieve ADDRESS_MANAGER_ADRESS when running locally

### ISSUE THREAD

**Issue by ben-chain** [ethereum-optimism/optimism#570] opened 2021-04-22 22:39 UTC
**Describe the bug**
Occasionally (e.g. for me, after a few tries), when spinning up the system with `docker-compose up -d`, I have a few services fall over due to a missing AM address from the environment.  I'm assuming this is some sort of race condition where we spin up those services a little too quickly.  If I start those services again it usually works.

**To Reproduce**
1. Follow `README.md` instructions to build master and get ready to spin it up.
2. Run something computationally heavy in the background like screen sharing in a google meet, another service, etc.
3. run `docker-compose up -d` and start integration tests
4. If it works, repeat 2. and 3. until it fails

I think I have seen this persist even when bringing again with the same volumes, but I cannot consistently reproduce it.

**Expected behavior**
System should consistently start up on the first try.

**Error Messages**
in the `message_relayer`:
```
Error: Must pass ADDRESS_MANAGER_ADDRESS
at main (/opt/optimism/packages/message-relayer/src/exec/run.ts:29:11)
at /opt/optimism/packages/message-relayer/exec/run-message-relayer.js:6:9
at Object.<anonymous> (/opt/optimism/packages/message-relayer/exec/run-message-relayer.js:7:3)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
at internal/main/run_main_module.js:17:47
```

in `batch_submitter`:
```
{"level":30,"time":1619130363690,"msg":"Starting batch submitter..."}
{"level":40,"time":1619130363690,"varName":"ADDRESS_MANAGER_ADDRESS","msg":"Missing environment variable"}
```

**System Specs:**
 - OS: Mac 11.2.1
 - Package Version (or commit hash): 1746244b02496ea4cf7a118a74803c2c562bd8c0

**Comment by ben-chain** [comment] 2021-04-22 22:39
@krebernisak can you confirm this is consistent with some flakiness you had at one point, or is that something else?

**Comment by TransmissionsDev** [comment] 2021-04-22 22:54
@ben-chain This happens to me frequently.

**Comment by snario** [comment] 2021-04-22 23:07
@ben-chain could you remove `--silent` from this line?

https://github.com/ethereum-optimism/optimism/blob/ab285e44acfca8d1b3a51cacdd14837cf956860e/ops/scripts/batches.sh#L5-L5

...and provide the logs you see from the `batch-submitter` Docker container when this error pops up?

**Comment by tynes** [comment] 2021-04-23 01:31
The solution for this is to run `docker-compose down` to remove the networks and stopped containers. This used to be abstracted away by `up.sh`

**Comment by TransmissionsDev** [comment] 2021-04-23 02:25
> The solution for this is to run `docker-compose down` to remove the networks and stopped containers. This used to be abstracted away by `up.sh`

I could swear I see this issue more frequently when I run `docker-compose down` and then start back up?

**Comment by TransmissionsDev** [comment] 2021-04-23 17:07
Yep I don't think running `docker-compose down` really helps, if anything I feel like I have a lower success rate right after I do a full kill.

**Comment by tynes** [comment] 2021-04-23 20:46
@krebernisak You should rebase because those logs are old, there were updates recently that removed them. Maybe that will solve it?

@TransmissionsDev I consistently experience the problem if I do not run the exact command after running a `docker-compose up`:

```
$ docker-compose down -v
```

My system:
```bash
$ docker --version
Docker version 19.03.12-ce, build 48a66213fe

$ docker-compose --version
docker-compose version 1.27.3, build unknown

$ uname -rom
5.5.10-arch1-1 x86_64 GNU/Linux
```

**Comment by krebernisak** [comment] 2021-04-24 10:38
@tynes I've deleted all images, re-cloned, `master@1743a6d`, tried a few times, and still the same `relayer` issue.

On the first run, the `dlt` container also exited quickly:

```
{"level":30,"time":1619259674007,"msg":"Service is starting..."}
{"level":30,"time":1619259674009,"msg":"Service is initializing..."}
{"level":30,"time":1619259674010,"msg":"Initializing L1 Data Transport Service..."}
Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
(node:1) UnhandledPromiseRejectionWarning: Error: Provided input for option "addressManager" is invalid: null
    at validateOptions (/opt/optimism/packages/core-utils/src/base-service.ts:133:13)
    at new BaseService (/opt/optimism/packages/core-utils/src/base-service.ts:23:5)
    at new L1IngestionService (/opt/optimism/packages/data-transport-layer/src/services/l1-ingestion/service.ts:62:5)
    at L1DataTransportService._init (/opt/optimism/packages/data-transport-layer/src/services/main/service.ts:70:39)
    at L1DataTransportService.init (/opt/optimism/packages/core-utils/src/base-service.ts:38:5)
    at L1DataTransportService.start (/opt/optimism/packages/core-utils/src/base-service.ts:53:5)
    at /opt/optimism/packages/data-transport-layer/src/services/run.ts:55:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After that, the `dlt` started ok on the subsequent runs.

But on the last run now (did not `compose down` this time), I've noticed an additional `l2geth` error:

```
INFO [04-24|10:28:44.603] Initialising Ethereum protocol           versions="[64 63]" network=420 dbversion=7
INFO [04-24|10:28:44.611] Loaded most recent local header          number=10 hash=0fc03b…f5ffcf td=21 age=2m55s
INFO [04-24|10:28:44.611] Loaded most recent local full block      number=10 hash=0fc03b…f5ffcf td=21 age=2m55s
INFO [04-24|10:28:44.611] Loaded most recent local fast block      number=10 hash=0fc03b…f5ffcf td=21 age=2m55s
TRACE[04-24|10:28:44.613] Loaded voting snapshot from disk         number=0  hash=f7bbe1…456695
DEBUG[04-24|10:28:44.616] Read timestamp from last block.          timestamp=1619259949
DEBUG[04-24|10:28:44.617] Reinjecting stale transactions           count=0
INFO [04-24|10:28:44.617] Loaded local transaction journal         transactions=0 dropped=0
INFO [04-24|10:28:44.617] Regenerated local transaction journal    transactions=0 accounts=0
INFO [04-24|10:28:44.618] Running in sequencer mode
INFO [04-24|10:28:44.619] Sanitizing timestamp refresh threshold to 15 minutes
INFO [04-24|10:28:44.619] Configured rollup client                 url=http://dtl:7878 chain-id=420 ctc-deploy-height=8
INFO [04-24|10:28:44.668] Found latest index                       index=1
ERROR[04-24|10:28:44.668] Unexpected number of transactions in block: %d LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ethereum/go-ethereum/rollup.(*SyncService).initializeLatestL1(0xc00051a780, 0xc000124a60, 0x0, 0x0)
	/go-ethereum/rollup/sync_service.go:243 +0xa65
github.com/ethereum/go-ethereum/rollup.NewSyncService(0x1539cc0, 0xc0004ef200, 0x1f018, 0x0, 0x100, 0x0, 0x895440, 0xc000038073, 0xf, 0x420a9dfae970b659, ...)
	/go-ethereum/rollup/sync_service.go:136 +0x5f9
github.com/ethereum/go-ethereum/eth.New(0xc00000e620, 0xc0000dcc00, 0x1212aa0, 0xc0004318a8, 0x42c718)
	/go-ethereum/eth/backend.go:212 +0xc5e
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc00000e620, 0xc00056c750, 0xc000431a28, 0xc00000e5e0, 0x2)
	/go-ethereum/cmd/utils/flags.go:1747 +0x3d
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc00033c000, 0x0, 0x0)
	/go-ethereum/node/node.go:206 +0x3f9
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc00033c000)
	/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc0000e2000, 0xc00033c000)
	/go-ethereum/cmd/geth/main.go:338 +0x70
main.geth(0xc0000e2000, 0x0, 0x0)
	/go-ethereum/cmd/geth/main.go:326 +0x12a
gopkg.in/urfave/cli%2ev1.HandleAction(0x10bf300, 0x134da68, 0xc0000e2000, 0xc000085080, 0x0)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00009a000, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5dd
main.main()
	/go-ethereum/cmd/geth/main.go:266 +0x55
```

**Comment by ben-chain** [comment] 2021-04-27 22:22
We have managed to isolate this bug to a networking issue, thanks again @tynes ! https://github.com/ethereum-optimism/optimism/pull/659

**Comment by platocrat** [comment] 2021-05-03 20:07
Confirmed with Ale from Synthetix that this issue with `kall` still occurs on a fresh clone, yarn install and build, and build of the docker containers of the monorepo.

@ben-chain @snario @tynes Are there any updates on a fix for this?

**Comment by TransmissionsDev** [comment] 2021-05-03 20:12
Can also reproduce.

**Comment by gakonst** [comment] 2021-05-03 21:19
@TransmissionsDev please share your `docker version` and `uname -a` for context

**Comment by TransmissionsDev** [comment] 2021-05-03 22:47
Yep:
```
benmayer@Bens-MacBook-Pro ~ % docker -v        
Docker version 20.10.5, build 55c4c88
benmayer@Bens-MacBook-Pro ~ % docker-compose version
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
benmayer@Bens-MacBook-Pro ~ % uname -a
Darwin Bens-MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 x86_64
```

**Comment by smartcontracts** [comment] 2022-03-25 15:15
Does this still happen to anyone?

**Comment by smartcontracts** [comment] 2022-03-27 17:12
Gonna close. If someone else runs into this again, we'll re-open.

**Closed by smartcontracts** 2022-03-27 17:12 UTC
Labels: C-bug, C-meta
